### ISSUE TITLE
getMore command doesn't use batchSize and maxTimeMS options

### ISSUE THREAD

**Issue by ja-jimenez** [zookzook/elixir-mongodb-driver#101]
Hi!

If we try to set the options **batch_size** and **max_time** when we execute the find or aggregation functions, the first query to Mongo use these options and we get the first batch correctly, but when the driver execute the get_more command, it cannot use these options again,  because these were deleted from options keyword in previous find/aggregate function, so get_more use default config, usually the rest of batch with 16MB size limit and no time out.

I'm using last version (0.7.4)

Regards!

**Comment by zookzook** [comment]
Yes, you are right: The options are getting dropped:

`    drop = ~w(limit hint single_batch read_concern max min collation return_key show_record_id tailable no_cursor_timeout await_data batch_size projection comment max_time skip sort)a`

I will fix it.
