### ISSUE TITLE
compilation error - elixir 1.12.2

### ISSUE THREAD

**Issue by AbducteeZero** [zookzook/elixir-mongodb-driver#102]
== Compilation error in file lib/mongo_db_connection/utils.ex ==
 ** (CompileError) lib/mongo_db_connection/utils.ex:66: cannot find or invoke local op_msg/1 inside match. Only macros can be invoked in a match and they must be defined before their invocation. Called as: op_msg(flags: _flags, sections: sections)
     lib/mongo_db_connection/utils.ex:66: (module)
 could not compile dependency :mongodb_driver, "mix compile" failed. You can recompile this dependency with "mix deps.compile mongodb_driver", update it with "mix deps.update mongodb_driver" or clean it with "mix deps.clean mongodb_driver"

**Comment by zookzook** [comment]
"mix deps.update mongodb_driver" looks like that you add the driver as a dependency. I guess you changed the driver. Please clean your build folder.
