### ISSUE TITLE
Timeout on initial command 

### ISSUE THREAD

**Issue by chris468** [zookzook/elixir-mongodb-driver#103]
I've been intermittently but often seeing a timeout from the initial mongo command on a given connection in when I run tests for my app. Other parts of the app have typically, if not always, successfully created and used other mongo connections, but I have confirmed in Compass that there are only a total of ~40 connections.

I was not successful in creating a small reproducing example, but I added some logs and suspect that there may be a race in topology.ex between [adding to waiting_pids when TopologyDescriptions.select_servers returns :empty](https://github.com/zookzook/elixir-mongodb-driver/blob/b7aa63c2ca3ff3466293d09b8994d3e396644fd8/lib/mongo/topology.ex#L264-L266) for :checkout_session, and [sending :new_connection for :connected](https://github.com/zookzook/elixir-mongodb-driver/blob/b7aa63c2ca3ff3466293d09b8994d3e396644fd8/lib/mongo/topology.ex#L183). Whenever there is a timeout, I see empty `state.waiting_pids` when `:new_connection` is sent, followed by select_servers returning :empty to :checkout_session. 

Here is a typical log when I see the timeout. [This branch](https://github.com/ni-kismet/elixir-mongodb-driver/tree/connect-timeout-logs) contains the added logs. Let me know if you need more info.

```
12:26:58.743 [info]  call_with_retries createCollection 0 #Function<4.27080005/0 in Helium.DB.MongoClient.create_collection/4>

12:26:58.743 [info]  issue_command :write [listCollections: 1]

12:26:58.743 [info]  #PID<0.653.0> Connected {"localhost:27017", #PID<0.654.0>}

12:26:58.746 [info]  #PID<0.653.0> connected: sending :new_connection to []

12:26:58.746 [info]  #PID<0.653.0> handle :checkout_session for {#PID<0.651.0>, [:alias | #Reference<0.3406635613.3192455171.192850>]}

12:26:58.746 [warn]  #PID<0.653.0> handle :checkout_session: select_servers returned :empty for {#PID<0.651.0>, [:alias | #Reference<0.3406635613.3192455171.192850>]}

12:26:58.750 [info]  #PID<0.653.0> handle :server_description: update

12:27:06.353 [info]  #PID<0.485.0> handle :server_description: update

12:27:08.508 [info]  #PID<0.562.0> handle :server_description: update

12:27:08.747 [info]  #PID<0.653.0> handle :server_description: update

12:27:16.355 [info]  #PID<0.485.0> handle :server_description: update

12:27:18.510 [info]  #PID<0.562.0> handle :server_description: update

12:27:18.749 [info]  #PID<0.653.0> handle :server_description: update

12:27:26.357 [info]  #PID<0.485.0> handle :server_description: update

12:27:28.512 [info]  #PID<0.562.0> handle :server_description: update

12:27:28.751 [info]  #PID<0.653.0> handle :server_description: update

12:27:36.359 [info]  #PID<0.485.0> handle :server_description: update

12:27:38.514 [info]  #PID<0.562.0> handle :server_description: update

12:27:38.753 [info]  #PID<0.653.0> handle :server_description: update

12:27:46.361 [info]  #PID<0.485.0> handle :server_description: update

12:27:48.516 [info]  #PID<0.562.0> handle :server_description: update

12:27:48.755 [info]  #PID<0.653.0> handle :server_description: update

12:27:56.363 [info]  #PID<0.485.0> handle :server_description: update

12:27:58.518 [info]  #PID<0.562.0> handle :server_description: update

12:27:58.745 [info]  Application user_repository exited: exited in: UserRepository.Application.start(:normal, [])
    ** (EXIT) exited in: GenServer.call(:mongo_users, {:checkout_session, :write, :implicit, [timeout: 4000, pool_timeout: 5000, connect_timeout_ms: 1000, pool_size: 20, read_preference: [mode: :primaryPreferred], write_counter: 1]}, 60000)
        ** (EXIT) time out
```

**Comment by zookzook** [comment]
I guess, it is a networking problem. Because it took to much time to establish a connection. The default timeout is 60 seconds. You can increase it by using the options `:checkout_timeout`

What kind of topology do you use? A singleton? Replica set? Mongos?

**Comment by chris468** [comment]
A networking problem was my initial suspicion as well, but I've tried to rule that out. I'm using a singleton, running in a docker container on the same ubuntu 20.04 vm as my app: `docker run -d   --name mongo -p 27017:27017 mongo:4.4`

I tried increasing `:checkout_timeout` to 180 seconds, still times out.
When I see my app hang, I can still reliably connect to the database using `mongosh` on the local vm.

**Comment by zookzook** [comment]
I guess, the reason is your deployment with docker. I started the MongoDB like you:
`docker run -d --name mongo -p 27017:27017 mongo:4.4`

then I started the connection
`{:ok, conn} = Mongo.start_link(url: "mongodb://localhost:27017/test")`

and inserted one document
`{:ok,
 %Mongo.InsertOneResult{
   acknowledged: true,
   inserted_id: #BSON.ObjectId<6123b50d306a5fc212467894>
 }}`

everything ok.

So, where is your application running and can you show me the configuration?

**Comment by chris468** [comment]
I have also reproduced with mongo installed locally. I have seen this running tests for the app on several machines locally. I just tried on a physical ubuntu 21.04 machine to rule out issues w/ vm setup, and was able to reproduce. I'm not sure if we've seen it in production. It does not reproduce every time, but if I run mix test in a loop it happens within minutes.

You can see my configuration in [this](https://github.com/chris468/mongo-timeout) was my attempt at reproducing with a simpler setup, although I haven't reproduced with that. There may be something else going on before the real app gets to this point, I can continue trying to make a simple reproducing case.

I understand that it's difficult if I can't give you an example that lets you reproduce, which was why I added some logging. If there's any other logging that would help or anything else you can recommend let me know. Otherwise I'll keep trying to come up with a simple reproducing case.

**Comment by 1st8** [comment]
FYI This happens to me with MongoDB 3.6, but not with 4.4.

Do you, by chance, have any idea if this can be fixed?

Thanks for the great work on this driver by the way!
