### ISSUE TITLE
Usage of @spec and Dialyzer

### ISSUE THREAD

**Issue by jgwmaxwell** [zookzook/elixir-mongodb-driver#107]
Hi,

Firstly - thanks for a great library, we've been using it to great success and we're super happy with how it performs in the real world.

We've run into some issues with the partial application of `@spec`, since we do use Dialyzer downstream of this. I've seen your commentary on issue #88 here: https://github.com/zookzook/elixir-mongodb-driver/issues/88#issuecomment-821801704 and respect your opinion on that. 

I do wonder however if you would be open to a PR that removes all `@spec` declarations, at least allowing downstream projects using Dialyzer to have it infer behaviours rather than be mislead in some places. It seems odd to me to have _some_ of the calls specced and others not, and hopefully a simple all-or-nothing policy would make maintenance easier?

Many thanks!

**Comment by zookzook** [comment]
Thank you very much for compliments. Yes, I can live without all those specs. I only left them in out of respect for the previous authors. If no one objects, then we can remove all the specs. And if I have lots and lots of time, I can rewrite specs and maybe get a gold star.

**Comment by jgwmaxwell** [comment]
I've removed them on a branch and validated that fixes downstream projects that use Dialyzer - I'm going to spend a while scoping what fixing would take and then open a PR for one of those two routes.

**Comment by zookzook** [comment]
Hey hey,

sorry, I don't care about the specs so far. The definition comes from a PR. But feel free to create PR that changes the specs. I will merge it!

**Comment by zookzook** [comment]
Closing due to no response.
