### ISSUE TITLE
Cannot connect to mongodb server via SSH tunnel

### ISSUE THREAD

**Issue by bluzky** [zookzook/elixir-mongodb-driver#111]
I'm using AWS DocumentDB and I'm trying to connect from my local machine via SSH tunnel.
I can connect successfully using command line. But when I connect using mongdb_driver, it doesn't work.
This is my connection options: 

```elixir
{Mongo,
     [
       # System.get_env("MONGODB_URL"),
       url:
         "mongodb://mIh30btgudj4:Pav9kmTGmxN8FGlPELGVxz6Mysv1OKVA@localhost:27017/platform_data?ssl=true&ssl_ca_certs=rds-combined-ca-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false",
       pool_size: 1,
       name: :mongo,
       ssl_opts: [
         cacertfile: "/home/flex/.ssh/rds-combined-ca-bundle.pem",
         server_name_indication: :disable
       ]
     ]}

```

I debug and see that the first time it connect successfully but after that it automatically update the hostname to real AWS hostname like `docdb.xxx.ap-southeast-1.docdb.amazonaws.com`.

Is there any existing option to make this work? Thank you

**Comment by zookzook** [comment]
Maybe it is a good idea to analyse the reason for crashing. Do you have some logs to share with the stack trace. I don't have access to an AWS DocumentDB instance.

**Comment by zookzook** [comment]
I just released version 0.8.0, because I did not get any response from other issues and I don't want to wait for it.

**Comment by zookzook** [comment]
Closing due to no response.

**Comment by retf** [comment]
I tried connecting in documentdb, but it's not working! any working example?

**Comment by zookzook** [comment]
I'm sorry. I don't have access to an AWS DocumentDB instance. Therefore I cannot provide an example.

**Comment by sonic182** [comment]
Can you please add an example to the docs @zookzook ?

I have an example using a global-bundle.pem (provided by aws when using DocumentDb):

```elixir
url = "mongodb://<myuser>:<mypassword>@<documentdbhost>:27017/<database>?tls=true&tlsCAFile=global-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false"


{:ok, conn} = Mongo.start_link([
  url: url,
  ssl_opts: [
    cacertfile: "global-bundle.pem",
  ]
])
```

basically they makes you to use SSL and provides you a custom cacertfile

**Comment by zookzook** [comment]
Thank you. Maybe I will do it next weekend!
