### ISSUE TITLE
Warning compiling library version 0.8.1

### ISSUE THREAD

**Issue by ja-jimenez** [zookzook/elixir-mongodb-driver#120]
Hi!

I'm testing the last version (0.8.1) and the compilation throws the next warning:

> warning: got "@impl true" for function checkin/1 but no behaviour specifies such callback. The known callbacks are:
> 
>   * DBConnection.checkout/1 (function)
>   * DBConnection.connect/1 (function)
>   * DBConnection.disconnect/2 (function)
>   * DBConnection.handle_begin/2 (function)
>   * DBConnection.handle_close/3 (function)
>   * DBConnection.handle_commit/2 (function)
>   * DBConnection.handle_deallocate/4 (function)
>   * DBConnection.handle_declare/4 (function)
>   * DBConnection.handle_execute/4 (function)
>   * DBConnection.handle_fetch/4 (function)
>   * DBConnection.handle_prepare/3 (function)
>   * DBConnection.handle_rollback/2 (function)
>   * DBConnection.handle_status/2 (function)
>   * DBConnection.ping/1 (function)
> 
>   lib/mongo/mongo_db_connection.ex:200: Mongo.MongoDBConnection (module)

Reviewing the DBConnection library I have seen the callback **_checkin_** has been removed from module in last version (2.4.1). I don't have experience using this library, so I am not sure if this warning could bring some problems or if  we could remove the checkin function from **mongo_db_connection.ex**.

**Comment by zookzook** [comment]
Good catch! I will fixed it!
