### ISSUE TITLE
ping fails periodically with DBConnection.ConnectionError

### ISSUE THREAD

**Issue by bodbdigr** [zookzook/elixir-mongodb-driver#121]
Hi,

Just wanted to flag that `Mongo.ping()` fails _periodically_ (less then 1% of cases) with `%DBConnection.ConnectionError{}` at https://github.com/zookzook/elixir-mongodb-driver/blob/master/lib/mongo.ex#L439 and subsequently at https://github.com/zookzook/elixir-mongodb-driver/blob/master/lib/mongo/error.ex#L193 as there's no function clause matching the `DBConnection.ConnectionError` not `Mongo.Error` relevant part of the trace below:

```
FunctionClauseError: no function clause matching in Mongo.Error.not_writable_primary_or_recovering?/2
  File "lib/mongo/error.ex", line 193, in Mongo.Error.not_writable_primary_or_recovering?/2
  File "lib/mongo.ex", line 439, in Mongo.issue_command/4
  File "lib/web/health.ex", line 9, in anonymous fn/2 in Warehouse.Web.Health.do_match/4
...
```

And thank you for the great lib!

**Comment by zookzook** [comment]
I will fix this! Thanks for the report.

**Comment by bodbdigr** [comment]
oh, that was lightning fast, thanks!

**Comment by zookzook** [comment]
By the way: it is not a good idea to use the health function to check the database :-) The health function should only check the health of the application.
