### ISSUE TITLE
Index creation on a large collection

### ISSUE THREAD

**Issue by mustardnoise** [zookzook/elixir-mongodb-driver#123]
Hi @zookzook,

I don't know if it's a bug or if I'm doing something wrong, but I'm facing the problem of creating indexes for a large collection. The index creation happens when the application starts, but since the collection is large and there is no async/background option, the client obviously gets timeouts and the application exists.  As a hack, I can catch the exit, but maybe there is a better way to handle this issue.

Mongo version 4.4

Error:

```sh
[error] Mongo.MongoDBConnection (#PID<0.10977.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.10839.0> timed out because it queued and checked out the connection for longer than 15000ms

#PID<0.10839.0> was at location:

    :prim_inet.recv0/3
    (mongodb_driver 0.8.4) lib/mongo_db_connection/utils.ex:100: Mongo.MongoDBConnection.Utils.recv_data/3
    (mongodb_driver 0.8.4) lib/mongo_db_connection/utils.ex:21: Mongo.MongoDBConnection.Utils.post_request/3
    (stdlib 3.17) timer.erl:166: :timer.tc/1
    (mongodb_driver 0.8.4) lib/mongo/mongo_db_connection.ex:299: Mongo.MongoDBConnection.execute_action/4
    (mongodb_driver 0.8.4) lib/mongo/mongo_db_connection.ex:241: Mongo.MongoDBConnection.handle_execute/4
    (db_connection 2.4.2) lib/db_connection/holder.ex:354: DBConnection.Holder.holder_apply/4
    (db_connection 2.4.2) lib/db_connection.ex:1364: DBConnection.run_execute/5
    (db_connection 2.4.2) lib/db_connection.ex:1459: DBConnection.run/6
    (db_connection 2.4.2) lib/db_connection.ex:652: DBConnection.execute/4
    (mongodb_driver 0.8.4) lib/mongo.ex:805: Mongo.exec_command_session/3
    (mongodb_driver 0.8.4) lib/mongo.ex:461: Mongo.issue_command/4
    (mongodb_driver 0.8.4) lib/mongo.ex:1374: Mongo.create_indexes/4

    ...

[notice] Application foo_bar exited: exited in: FooBar.Application.start(:normal, [])
    ** (EXIT) "mongo:27017 tcp recv: unknown POSIX error - :closed"
```

**Comment by zookzook** [comment]
Hi @mustardnoise,

it is not a bug, it is a timeout. You can increase it:

https://hexdocs.pm/mongodb_driver/Mongo.html#module-generic-options

It comes from the DBConnection module! Hope that helps!

**Comment by mustardnoise** [comment]
Thanks for the quick reply @zookzook. Yes, I know about the `:timeout` option, I was just wondering if there is a better way to handle this because when there are millions of records it can take a while (hours depending on how many records there are) for an index to be created.

**Comment by zookzook** [comment]
Ok, I will take a look. Maybe we can a timeout option like `:infinity` for these kind of operation.

**Comment by zookzook** [comment]
Since this timeout comes from DBConnection, maybe you can use `:timeout` as an option when creating the indexes, like this:

```elixir
Mongo.create_indexes(:mongo, "my-big-collection", indexes, timeout: :infinity)
```

The option should be pipelined to DBConnection and DBConnection will use it:

```elixir
  timeout = Keyword.get(opts, :timeout, state.timeout)

 ...

case :timer.tc(fn -> Utils.post_request(op, state.request_id, %{state | timeout: timeout}) end) do  
```
