### ISSUE TITLE
BSON.Objectid 

### ISSUE THREAD

**Issue by YIU-combinator** [zookzook/elixir-mongodb-driver#130]
Thanks for providing a feature-rich MongoDB alternative library. The recent Mongo.Repo addition is a real Godsend.  
It simplifies a lot of things. I am still playing around with the library. Recently I stumbled upon certain issues, BSON objects being on top of the list.

iex -S mix
iex(1) Mongo.delete_one(:mongo, "books", #BSON.ObjectId<6269f92d8766258ec23664fd>) 

Nothing deleted. iex returns no prompt, nothing.

**Comment by zookzook** [comment]
You need to specify a query/filter for deleting:

```
h Mongo.delete_one

                                 def delete_one(topology_pid, coll, filter, opts \\ [])

  @spec delete_one(GenServer.server(), collection(), BSON.document(), Keyword.t()) :: result(Mongo.DeleteResult.t())

Remove a document matching the filter from the collection.
```
By the way: # is used for inline comments, that means:

```elixir
Mongo.delete_one(:mongo, "books", #BSON.ObjectId<6269f92d8766258ec23664fd>)
``` 

is something like this:

```elixir
Mongo.delete_one(:mongo, "books",
```

Example:

```elixir
Mongo.delete_one(:mongo, "books", %{_id: the_id})

**Comment by YIU-combinator** [comment]
`iex(9)> Mongo.delete_one(:mongo, "books", %{_id: "6269f92d8766258ec23664fd"})  
{:ok, %Mongo.DeleteResult{acknowledged: true, deleted_count: 0}}

iex(10)> Mongo.delete_one(:mongo, "books", %{_id: "BSON.ObjectId<6269f92d8766258ec23664fd>"})
{:ok, %Mongo.DeleteResult{acknowledged: true, deleted_count: 0}}

iex(11)> Mongo.delete_one(:mongo, "books", %{_id: "#BSON.ObjectId<6269f92d8766258ec23664fd>"})
{:ok, %Mongo.DeleteResult{acknowledged: true, deleted_count: 0}}

iex(12)> Mongo.delete_one(:mongo, "books", %{_id: "ObjectId<6269f92d8766258ec23664fd>"})      
{:ok, %Mongo.DeleteResult{acknowledged: true, deleted_count: 0}}

iex(13)> Mongo.delete_one(:mongo, "books", %{_id: "ObjectId(6269f92d8766258ec23664fd)"})
{:ok, %Mongo.DeleteResult{acknowledged: true, deleted_count: 0}}`

Nothing deleted still. Something went wrong?

**Comment by zookzook** [comment]
`BSON.ObjectId.decode!("6269f92d8766258ec23664fd")` will help.

**Comment by YIU-combinator** [comment]
```
iex(2)> Mongo.delete_one(**:mongo**, "books", %{_id: "6269f92d8766258ec23664fd" |> BSON.ObjectId.decode!}) 
{:ok, %Mongo.DeleteResult{acknowledged: true, deleted_count: 1}}
```
It works as expected! Thanks a lot! One more thing: 
I use Mongo.Repo to connect to the MongoDB back-end. By default, It's required to specify which database to connect. Then such connection is bounded to the topology **:mongo** as seen above. The problem is I would like to build a single JSON API back-end that serves multiple websites, each having a separate database and collections (one mongo database for abc.com, another for xyz.com etc) 

How to achieve that goal? 

Thanks in advance for your time and expertise!

**Comment by zookzook** [comment]
You can use the `database` option in each query:

https://github.com/zookzook/elixir-mongodb-driver/blob/acbddff92618e44fd81a6908b5d5ef2c4fa69e99/lib/mongo.ex#L24

Or use an additional topology for each database.

**Comment by YIU-combinator** [comment]
```
defmodule Mongo2 do
  import Mongo
  def child_spec(opts) do
    %{
      id: __MODULE__,
      start: {__MODULE__, :start_link, [opts]},
      type: :worker,
      restart: :permanent,
      shutdown: 500
    }
  end
end
```

I tried to add a new module. 
iex -S mix returns

```
** (Mix) Could not start application mongoex: Mongoex.Application.start(:normal, []) returned an error: shutdown: failed to start child: Mongo2
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function Mongo2.start_link/1 is undefined or private
            (mongoex 0.1.0) Mongo2.start_link([name: :mongo2, url: "mongodb://localhost:27017", timeout: 60000, idle_interval: 10000, queue_target: 5000, database: "abc-dot-com"])
```

**Comment by zookzook** [comment]
Keep in mind, that each topology has it's own connection pool.

**Comment by YIU-combinator** [comment]
There are some confusions about the connection pool and db connections.

1) By default, the Mongo module starts with four processes connected to the supervisor, whether I change the pool_size option to 2 or to 10.  How can I see the pool size in :observer.start ?

2) The most striking thing is that there is no error reporting even I cut off the database connection, or start with non-existing database name.

The previous iteration of code was refactored to adapt DynamicSupervisor. Here is the code:   

```
defmodule DbApi.DyDBStarter do
  use DynamicSupervisor
  @database_list ~w(bookstore cortex_com blahblah_com)

  # Client

  def start_link(_arg) do
    DynamicSupervisor.start_link(__MODULE__, :ok, name: __MODULE__)
  end

  # Server

  def init(:ok) do
    DynamicSupervisor.init(strategy: :one_for_one)
  end

  def start_all_db_workers() do
    for db <- @database_list do
      start_db_worker(db)
    end
  end

  def start_db_worker(db) do
    spec = {
      Mongo,
      database: db,
      url: "mongodb://localhost:27017",
      name: String.to_atom(db),
      pool_size: 10
    }
    DynamicSupervisor.start_child(__MODULE__, spec)
  end
end

```

To start the children automatically in application.ex

```
def start(_type, _args) do
    children = [
      #...phoenix children...
      DbApi.DyDBStarter,
      {Task, &DbApi.DyDBStarter.start_all_db_workers/0}
    ]
    opts = [strategy: :rest_for_one, name: DbApi.Supervisor]
    Supervisor.start_link(children, opts)
  end

```

**Comment by YIU-combinator** [comment]
BTW, **DynamicSupervisor.terminate_child/2**  takes a module name and a pid. topology_pid is not accepted. 
How can I find the pid to terminate the child?

**Comment by zookzook** [comment]
> By default, the Mongo module starts with four processes connected to the supervisor, whether I change the pool_size option to 2 or to 10. How can I see the pool size in :observer.start ?

The pool is managed by DBConnection. You can see it in :observer.start, because the pool is managed by using `:ets` tables.

>The most striking thing is that there is no error reporting even I cut off the database connection, or start with a non-existing database name.

Database are created on demand. You never get an error, because the database is not there.

A `DynamicSupervisor` is used, if you create and terminate processes. In your case it looks like, that you just create a *static` supervisor. I would put the three topology server to the application supervisor. In this case you can use the `: bookstore` atom to address the database. In case of `DynamicSupervisor` you can use the `via` option to create a mapping between strings and process names used in the `DynamicSupervisor`. See Registry.lookup for more information about it.

**Comment by zookzook** [comment]
I close this issue. Feel free to open it again, if you have some questions.
