### ISSUE TITLE
Crash activating logs using Elixir version smaller than 1.13

### ISSUE THREAD

**Issue by ja-jimenez** [zookzook/elixir-mongodb-driver#132]
Hi!

I'm testing the last version (0.9.0) and when I compile I get this warning:

`
==> mongodb_driver
Compiling 52 files (.ex)
warning: Inspect.Opts.new/1 is undefined or private
  lib/mongo.ex:1827: Mongo.to_iodata/1
`
Reviewing the code, I have seen that this code fragment is used to print logs, so if we activate logs using Elixir version smaller than 1.13 (Inspect.Opts.new/1 included in this version) we get a crash.

Regards.

**Comment by zookzook** [comment]
I will fix it and provide a workaround for Elixir version < 1.13

**Comment by zookzook** [comment]
Please try the current master branch. If this is working, I would draft a new release 0.9.1!

**Comment by ja-jimenez** [comment]
I was testing with Elixir 1.12.3 (and 1.13.4) and different configs for mongodb_driver (logs set to true, false and debug) and now it's working.

Thanks!

**Comment by zookzook** [comment]
Draft a new release 0.9.1 that contains the fix.
