### ISSUE TITLE
Mongo.find only retrieving one batch_size worth of documents

### ISSUE THREAD

**Issue by HWideman** [zookzook/elixir-mongodb-driver#133]
When using Mongo.find like so: 
`Mongo.find(:mongo, "objects", %{}, limit: 400, batch_size: 50)`

I am only ever returned `batch_size` documents. So in the above example I would only get 50 documents returned. If I set `batch_size` to 500, only then would I get 400 documents returned.

Using release 0.9.0 and mongodb-community@5.0

Any suggestions on how to debug this?

**Comment by zookzook** [comment]
You get a stream as a result:

```elixir
Mongo.find(:mongo, "objects", %{}, limit: 400, batch_size: 50) |> Enum.to_list()
```

or remove the limit to get all
```elixir
Mongo.find(:mongo, "objects", %{}, batch_size: 500) |> Enum.to_list()
```

**Comment by HWideman** [comment]
> 

Ah I see, I was pulling docs straight off of the stream 🙃  

Thank you for your help!

**Comment by zookzook** [comment]
You are welcome!
