### ISSUE TITLE
Cannot call `Mongo.start_link()`

### ISSUE THREAD

**Issue by devcayed** [zookzook/elixir-mongodb-driver#137]
**Disclaimer:** I am fairly new to Elixir so this issue might not be caused by the driver but by something else on my system!

Anyway, I've followed the README and added the dependency to my `mix.exs` file and tried opening a single connection using
```ex
{:ok, conn} = Mongo.start_link(url: "mongodb://localhost:27017/")

cursor = Mongo.find(conn, "test-collection", %{})

cursor
|> Enum.to_list()
|> IO.inspect

```
(basically copying the code sample from the README).

However, invoking `start_link` is highlighted as error with the following message:

```
(MatchError) no match of right hand side value: {:error, {%ArgumentError{message: "unknown registry: :events_registry"},
[{Registry, :key_info!, 1, [file: 'lib/registry.ex', line: 1343]}, {Registry, :dispatch, 4, [file: 'lib/registry.ex', line: 464]},
{Mongo.Topology, :init, 1, [file: 'lib/mongo/topology.ex', line: 124]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 423]},
{:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 390]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}}

Stacktrace:
  │ lib/mongoelixir.ex:7: (file)
  │ (elixir 1.13.2) lib/kernel/parallel_compiler.ex:346: anonymous fn/5 in Kernel.ParallelCompiler.spawn_workers/7Elixir
```

Have I messed up or this is an issue with the driver?

Thanks a lot for any help in advance!

**Comment by zookzook** [comment]
```elixir
iex -S mix
Erlang/OTP 24 [erts-12.2] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1]

Interactive Elixir (1.13.2) - press Ctrl+C to exit (type h() ENTER for help)
iex [17:34 :: 1] > {:ok, conn} = Mongo.start_link(url: "mongodb://localhost:27017/my-database")
{:ok, #PID<0.244.0>}
iex [17:34 :: 2] >
```

I have no issues. How do you start your application?

**Comment by devcayed** [comment]
Initially, I haven't even tried running as Visual Studio Code already highlighted said line as error.

After trying both `iex -S mix` and `mix run`, they resulted in the following error:
```
== Compilation error in file lib/mongo/mongo_db_connection.ex ==
** (CompileError) lib/mongo/mongo_db_connection.ex:292: undefined function op_msg/1 (expected Mongo.MongoDBConnection to define such a function or for it to be imported, but none are available)

could not compile dependency :mongodb_driver, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile mongodb_driver", update it with "mix deps.update mongodb_driver" or clean it with "mix deps.clean mongodb_driver"
```

Compiling, updating and cleaning as advised in the error message had no changing effect, sadly.

**Comment by zookzook** [comment]
Try to clean all the builds and try again. Did you changed the driver?

**Comment by zookzook** [comment]
`rm -rf _build`

**Comment by devcayed** [comment]
No! I literally just started trying to use this driver as it's the only one I've found that supports newer MongoDB versions...
I could not get past the sample code from the README though lol.

Removing all builds and running it (both ways) leads to the same error I've mentioned in my original comment.

**Comment by zookzook** [comment]
Maybe you can create a repository, so I can reproduce the compiler error.

**Comment by devcayed** [comment]
https://github.com/devcayed/elixir-mongodb
There you go.

**Comment by zookzook** [comment]
```
    lib/lmao.ex:1: (file)
```
lmao.ex is not a valid elixir source file.

**Comment by zookzook** [comment]
```elixir
defmodule Lmao do

	def test() do
		{:ok, conn} = Mongo.start_link(url: "mongodb://localhost:27017/ttv-players")

		cursor = Mongo.find(conn, "players", %{})

		cursor
		|> Enum.to_list()
		|> IO.inspect()
	end

end
```

**Comment by zookzook** [comment]
After that changes:

```
➜  elixir-mongodb git:(main) mix compile
Compiling 1 file (.ex)
Generated lmao app
➜  elixir-mongodb git:(main) ✗ iex -S mix
Erlang/OTP 24 [erts-12.2] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1]

Interactive Elixir (1.13.4) - press Ctrl+C to exit (type h() ENTER for help)
iex [19:21 :: 1] > Lmao.test()
[]
[]
```

**Comment by devcayed** [comment]
Oh man... Calling single methods and printing their result worked without defining a module so I figured this should work too.
Sorry for wasting your time & much appreciation for your help!
