### ISSUE TITLE
Migrating from Mongodb

### ISSUE THREAD

**Issue by YasirAsar** [zookzook/elixir-mongodb-driver#139]
Hello, @zookzook I intend to switch over to this library from `elixir-mongo/mongodb`. For the past two years, I have used that library. I therefore have a tonne of production data. as soon as I transfer from that library to this library. What exactly do I need to keep in mind?

**Comment by zookzook** [comment]
Keep in mind, that this driver has no support for Ecto related stuff. But the rest should work as expected, maybe some functions has other names or other parameters.

**Comment by YasirAsar** [comment]
Okey, So, I need to do full set of test after changing the library. Thanks for the quick reply.
