### ISSUE TITLE
Periodic timeouts if :timeout is less than or equal to the StreamingHelloMonitor heartbeat frequency

### ISSUE THREAD

**Issue by JD-Robertson** [zookzook/elixir-mongodb-driver#144]
I've been debugging an issue where a microservice would periodically report an error like:

`Mongo.MongoDBConnection (#PID<0.13156.11>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.13152.11> timed out because it queued and checked out the connection for longer than 4000ms\n\n#PID<0.13152.11> was at location:\n\n    :prim_inet.recv0/3\n    (mongodb_driver 0.9.1) lib/mongo_db_connection/utils.ex:100: Mongo.MongoDBConnection.Utils.recv_data/3\n    (mongodb_driver 0.9.1) lib/mongo_db_connection/utils.ex:20: Mongo.MongoDBConnection.Utils.post_request/3\n    (stdlib 3.15) timer.erl:166: :timer.tc/1\n    (mongodb_driver 0.9.1) lib/mongo/mongo_db_connection.ex:310: Mongo.MongoDBConnection.execute_action/4\n    (mongodb_driver 0.9.1) lib/mongo/mongo_db_connection.ex:252: Mongo.MongoDBConnection.handle_execute/4\n    (db_connection 2.4.2) lib/db_connection/holder.ex:354: DBConnection.Holder.holder_apply/4\n    (db_connection 2.4.2) lib/db_connection.ex:1364: DBConnection.run_execute/5\n"`

The service was specifying a timeout of 4000ms for all Mongo operations, but none of those operations was taking more than a few milliseconds to complete. Yet we were still seeing periodic timeouts, and operations that were in progress when one of those timeouts fired could fail with a connection closed exception. 

Experimentation showed that a timeout >10s avoided the issue. After some more digging around I determined that the StreamingHelloMonitor module was using the timeout passed in from the service for its connection even though that timeout was smaller than the hardcoded heartbeat interval and would always result in a timeout. 

I suspect I can just use a longer timeout for my use case to work around this, but long-term it would be good if the monitor either overrode the timeout for its connection or else made the heartbeat frequency configurable.

**Comment by zookzook** [comment]
I think, it is time to refactor the timeout stuff. Thanks for reporting!

**Comment by JD-Robertson** [comment]
Thanks! I upped the timeouts we were using to a safe range today and if fixed the issue on our end.

**Comment by JD-Robertson** [comment]
We are 13 commits behind the head right now and entering a stabilization phase so I'm going to hold off on pulling in this change for a couple weeks. However, I hacked up a local build and verified that your fix solves the issue I was seeing in my test setup.

**Comment by JD-Robertson** [comment]
Ok, so we found an issue with increasing the timeout and I'm trying to pull in the latest driver changes. It looks like I can no longer connect to MongoDB 4.4. I get an error like:

`"Mongo.MongoDBConnection (#PID<0.5740.0>) failed to connect: ** (Mongo.Error) \"helloOk\" had the wrong type. Expected bool, found int 14"`

Things work fine with Mongo 5 or 6.

Is that expected? Is there a new setting I need to update?

**Comment by zookzook** [comment]
> Is that expected? Is there a new setting I need to update?
No, it isn't. I think it is a bug. I think the specification regarding the handshake is little confusing. The specification mixes `helloOk: 1` and `helloOk: true`. I need to change the value to `true`.

**Comment by JD-Robertson** [comment]
I think I'm still seeing an issue. I'm not sure how I missed this with my initial validation, but there are two overloads of StreamingHelloMonitor.hello_command, one which takes a version and one which does not. The timeout is not modified in StreamingHelloMonitor.hello_command/3, and when that is called with the timeout set to 4s I still see timeouts.

**Comment by JD-Robertson** [comment]
Correction: The call to Mongo.exec_hello/2 which results in a timeout is coming from Monitor.get_server_description

**Comment by JD-Robertson** [comment]
Apologies, my initial assessment was incorrect. The issue I'm seeing is that after the initial hello command is sent the StreamingHelloMonitor.get_server_description function will call Mongo.exec_more_to_come. The opts bundle for this call has reverted back to the default timeout which is not sufficient for the long-running more_to_come operation, resulting in timeouts.

**Comment by zookzook** [comment]
Thanks for the detailed reporting. I will check the more_to_come call as soon as possible and provide a fix. I wonder why you decrease the timeout to 4s? What was the rational for it?

**Comment by JD-Robertson** [comment]
I don't know why the timeout is 4s. This component pre-dates my time on the project and the responsible parties are no longer around. However, when we tried to increase it back to 15s a lot of things started failing with no clear explanation as to why. Unlocking that puzzle is on my todo list.

**Comment by zookzook** [comment]
I fixed the timeout issue in the StreamingHelloMonitor.get_server_description function. Feel free to test it (master branch). If everything works like expected, then it is time to release a new version.

**Comment by JD-Robertson** [comment]
I've had the latest changes running for around an hour and everything looks good. Thanks for the help.
