### ISSUE TITLE
Having a basic problem establishing db connection

### ISSUE THREAD

**Issue by dmarko484** [zookzook/elixir-mongodb-driver#15]
I'm using latest {:mongodb_driver, "~> 0.5.3"} ... now in iex when I call Mongo.start_link/1 I'm getting error message like below. Any idea what's wrong? I'm running Mongodb 3.6.5 and no auth is required so it should work ...

Interactive Elixir (1.8.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> {:ok, conn} = Mongo.start_link(url: "mongodb://localhost:27017/database1")
{:ok, #PID<0.251.0>}
iex(2)> 
15:25:29.920 [error] GenServer #PID<0.255.0> terminating
** (RuntimeError) connect raised MatchError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (mongodb_driver) lib/mongo/mongo_db_connection.ex:147: Mongo.MongoDBConnection.driver/1
    (mongodb_driver) lib/mongo/mongo_db_connection.ex:137: Mongo.MongoDBConnection.hand_shake/2
    (mongodb_driver) lib/mongo/mongo_db_connection.ex:53: Mongo.MongoDBConnection.connect/2
    (db_connection) lib/db_connection/connection.ex:66: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Mongo.MongoDBConnection
** (EXIT from #PID<0.249.0>) shell process exited with reason: killed

**Comment by zookzook** [comment]
What kind of OS do you use?

I think, this line 
`String.split(to_string(:erlang.system_info(:system_architecture)), "-")`
does not work with your OS.

**Comment by zookzook** [comment]
I think it is a Windows OS. I will check, what Windows print by calling `:erlang.system_info(:system_architecture))` and make the function safer.

**Comment by zookzook** [comment]
Ok:

```
PS C:\Users\IEUser> iex.bat
Interactive Elixir (1.8.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> :erlang.system_info(:system_architecture)
'win32'
iex(2)>
```
I will fix this.

**Comment by zookzook** [comment]
Please update the driver to version 0.5.5!
