### ISSUE TITLE
inserted_at timestamp is greater than updated_at timestamp for new documents

### ISSUE THREAD

**Issue by jtokoph** [zookzook/elixir-mongodb-driver#151]
Example output of `SomeCollection.new` with timestamps enabled:

```
inserted_at: ~U[2022-10-22 23:43:50.140166Z],
updated_at: ~U[2022-10-22 23:43:50.140156Z]
```

In my opinion, it's wrong to have an `inserted_at` timestamp be later than the `updated_at` timestamp. Something shouldn't be able to have been updated before it was created. 

In an ideal world, the two values are identical at creation, but at a minimum the order should be flipped.

Here is how mongoid does it if there is a new record with both timestamps enabled:
https://github.com/mongodb/mongoid/blob/e24bc8349fb412cbdf1c316d0fff716bc81d01e5/lib/mongoid/timestamps/created.rb#L24-L31

**Comment by zookzook** [comment]
This issue is resolved. Thanks for pointing this out.
