### ISSUE TITLE
Replica set nodes not being replaced for new primary on primary fail, as expected.

### ISSUE THREAD

**Issue by ThomasGl** [zookzook/elixir-mongodb-driver#152]
I am starting the mongo instances from a `docker-compose.yml` file. Which when debugged through mongosh is behaving as expected, also the mongo driver for python: pymongo does this rotation of nodes seamless through the background.

For best experience on recreating this phenomena I would recommend using a python notebook and having in one cell:

```python
from pymongo import MongoClient
client = MongoClient('mongodb://mongo1,mongo2,mongo3/?replicaSet=mongoSet&readPreference=secondaryPreferred')
```

Where mongo1, mongo2, mongo3, respectively, correspond to 3 members in a replSet configuration passed to the primary node.

Then running a next cell:

```python

import random
from datetime import datetime
from time import sleep

DB = "mock"
COL = "chat"
ITEMS = 10

mydb = client[DB]
mycol = mydb[COL]

mylist = [
    {
        "msgs": [
            {
                "created_at": datetime.utcnow(),
                "content": "abc"*int((random.random()**3)*10)},
            {
                "created_at": datetime.utcnow(),
                "content": "abc"*int((random.random()**2)*10)}
        ]
    } for index in range(ITEMS) if random.seed(index) is None]

mycol.insert_many(mylist)
```

would append data for some specific collection,

then through terminal cmd, stopping the container in charge of the primary node (e.g. assume its the contianer named mongo1):

```bash
docker stop mongo1
```

Such change can be validated through:

```bash
docker exec -it mongo2 mongosh
```

and inside the mongo shell running `rs.status()`

Now even without running the first python notebook again, which would generate a new connection client, we can run the following:

```python
msgs = mycol.find({})
for elm in msgs:
    print(elm)
```

and get the documents stdout accordingly.

Now, I suppose we were to expect a similar behavior under mongodb-driver for elixir, where a background recoonection would take place to connect to the new primary member in the replica set. Yet, upon stopping the primary node connection for the test purpose using the code mentioned above: `docker stop mongo1`, I get the following warning and error messages:

```elixir
[warning] Unable to round trip time because of {:error, %Mongo.Error{code: 91, error_labels: [], fail_command: false, host: nil, message: "The server is in quiesce mode and will shut down", not_writable_primary_or_recovering: true, resumable: true, retryable_reads: false, retryable_writes: true}}
[error] Mongo.MongoDBConnection (#PID<0.610.0>) disconnected: ** (Mongo.Error) mongo1:27017 tcp recv: unknown POSIX error - :closed
[error] Mongo.MongoDBConnection (#PID<0.621.0>) disconnected: ** (Mongo.Error) mongo1:27017 tcp recv: unknown POSIX error - :closed
[error] Mongo.MongoDBConnection (#PID<0.621.0>) failed to connect: ** (Mongo.Error) mongo1:27017 tcp connect: non-existing domain - :nxdomain
[warning] Unable to round trip time because of {:error, %Mongo.Error{code: nil, error_labels: nil, fail_command: nil, host: "mongo1:27017", message: "mongo1:27017 tcp recv: unknown POSIX error - :closed", not_writable_primary_or_recovering: nil, resumable: true, retryable_reads: nil, retryable_writes: nil}}
```

Such is a yield after starting a pid with the following code under elixir iex -S mix:

```elixir
{:ok, pid} = Mongo.start_link(database: "mock", seeds: ["mongo1:27017", "mongo2:27017", "mongo3:27017"])
```

which yielded a response of:

```elixir
{:ok, #PID<0.594.0>}
```

Which works for future calls: e.g. find operations, insert, etc. But as described above, after stopping the primary mongo container we get the responses mentioned above.

I assume the solution is something to do with the response delay time the driver should behave with while the mongo configuration is being changed for a new primary, or perhaps access the mongosh to get the new primary node.

**Comment by zookzook** [comment]
Did you use a supervisor?

**Comment by ThomasGl** [comment]
Not in this case, I have a project directory with a couple of files and running it through the supervisor or in a simple demonstration as I mentioned above it yields the same behavior. Initial warnings when the container is stopping, leading to a an initial sequence of errors:

```elixir
[error] Mongo.MongoDBConnection (#PID<0.643.0>) disconnected: ** (Mongo.Error) mongo1:27017 tcp recv: unknown POSIX error - :closed
```

followed by an infinite loop of errors as:

```elixir
[error] Mongo.MongoDBConnection (#PID<0.920.0>) failed to connect: ** (Mongo.Error) mongo1:27017 tcp connect: non-existing domain - :nxdomain
```

**Comment by zookzook** [comment]
Can you provide the Docker files to create your replicaset? The error that your mentioned means, that the name "mongo1" could not be resolved. That is a DNS issue.

**Comment by ThomasGl** [comment]
Sure! Ill make a gist asap with the dockerfile and shell script I used to start the replSet. I will reply to this comment once I make the deploy, which I expect should be in least then 2 hours.

I understand the issue report. The thing is, according to the mongo documentation I shouldn't get a DNS error as the mongo engine should reinstate the connection to a secondary node, which became a primary node. I assume that in a case of having a DNS error whilst having a replica set connection url, we should some expect behaviour in order to search for this new primary node for reconnectioning 

I tested such behavior under the python engine for mongo: pymongo as described in the issue description listed above. And this behavior in the previous paragraph does take place

**Comment by ThomasGl** [comment]
Hey, I made the gist with the files and some basic instructions. Let me know if you have any issues.

link: https://gist.github.com/ThomasGl/2ca7618758b6fe149f6de20e9228c16c

**Comment by zookzook** [comment]
Thank you. I will try it out, but not today...maybe tomorrow.

**Comment by ThomasGl** [comment]
Amazing, thank you so much!

**Comment by zookzook** [comment]
If I try the docker-compose stuff, I'm not able to connect to the instances using the name "mongo1" etc:
```
18:47:49.455 [error] Mongo.MongoDBConnection (#PID<0.494.0>) failed to connect: ** (Mongo.Error) mongo2:27017 tcp connect: non-existing domain - :nxdomain (module=DBConnection.Connection function=connect/2 line=103 )
18:47:49.603 [error] Mongo.MongoDBConnection (#PID<0.498.0>) failed to connect: ** (Mongo.Error) mongo3:27017 tcp connect: non-existing domain - :nxdomain (module=DBConnection.Connection function=connect/2 line=103 )
18:47:49.975 [error] Mongo.MongoDBConnection (#PID<0.490.0>) failed to connect: ** (Mongo.Error) mongo1:27017 tcp connect: non-existing domain - :nxdomain (module=DBConnection.Connection function=connect/2 line=103 )
```

**Comment by zookzook** [comment]
I think, it is better to use a native MongoDB replica set to avoid side effects from Docker and network bridge magic at all.

**Comment by ThomasGl** [comment]
> If I try the docker-compose stuff, I'm not able to connect to the instances using the name "mongo1" etc:
> 
> ```
> 18:47:49.455 [error] Mongo.MongoDBConnection (#PID<0.494.0>) failed to connect: ** (Mongo.Error) mongo2:27017 tcp connect: non-existing domain - :nxdomain (module=DBConnection.Connection function=connect/2 line=103 )
> 18:47:49.603 [error] Mongo.MongoDBConnection (#PID<0.498.0>) failed to connect: ** (Mongo.Error) mongo3:27017 tcp connect: non-existing domain - :nxdomain (module=DBConnection.Connection function=connect/2 line=103 )
> 18:47:49.975 [error] Mongo.MongoDBConnection (#PID<0.490.0>) failed to connect: ** (Mongo.Error) mongo1:27017 tcp connect: non-existing domain - :nxdomain (module=DBConnection.Connection function=connect/2 line=103 )
> ```

**Comment by ThomasGl** [comment]
> If I try the docker-compose stuff, I'm not able to connect to the instances using the name "mongo1" etc:
> 
> ```
> 18:47:49.455 [error] Mongo.MongoDBConnection (#PID<0.494.0>) failed to connect: ** (Mongo.Error) mongo2:27017 tcp connect: non-existing domain - :nxdomain (module=DBConnection.Connection function=connect/2 line=103 )
> 18:47:49.603 [error] Mongo.MongoDBConnection (#PID<0.498.0>) failed to connect: ** (Mongo.Error) mongo3:27017 tcp connect: non-existing domain - :nxdomain (module=DBConnection.Connection function=connect/2 line=103 )
> 18:47:49.975 [error] Mongo.MongoDBConnection (#PID<0.490.0>) failed to connect: ** (Mongo.Error) mongo1:27017 tcp connect: non-existing domain - :nxdomain (module=DBConnection.Connection function=connect/2 line=103 )
> ```

To get this part correct, you should be starting an elixir env as: `iex -S mix`.

and if you run the following command you should obtain:

```elixir
{:ok, pid} = Mongo.start_link(url: "mongodb://mongo1,mongo2,mongo3/mock?replicaSet=mongoSet&readPreference=secondaryPreferred")
{:ok, #PID<0.716.0>}
```

Let me know what happens to you if after running the shell script, you run the following:

```bash
docker exec -it mongo1 mongosh
```

if it works it, should yield a mongo shell access to the mongo instance running within the container. Thus, if you then run `rs.status()` it should print the members of the replica set along with the primary/secondary values to each member. It should automatically denominate mongo1 as the primary, due to the constrains I applied to the docker-compose file.

Let me know if you have any issues.

**Comment by ThomasGl** [comment]
To check the full functionality of what I described at the initial description for this issue topic, please do take the time to test it with the python mongo driver. It has this inherit feature of reconnecting replica sets upon primary failure and a new one being replaced as primary.

**Comment by ThomasGl** [comment]
Hey there,

I was checking the functionality and I did perhaps some big mistake. The pid connection still works, thus the rotation to a new primary node does take place. Only that when one of the nodes is down we keep logging warning and error messages, which stops once the container is available again.

**Comment by zookzook** [comment]
Thanks for your efforts, asking questions about the whole stuff is always welcome. The monitor process logs this warnings for debugging purpose.

**Comment by ThomasGl** [comment]
My pleasure. Just trying to help others in the process as well
