### ISSUE TITLE
Ability to import formatter configuration

### ISSUE THREAD

**Issue by numso** [zookzook/elixir-mongodb-driver#159]
This project's .formatter.exs has some macros listed in `:locals_without_parens`. Today, I need to copy those into my .formatter.exs and keep them in sync. I'd love to be able to add `import_deps: [:mongodb_driver]` to my .formatter.exs instead.

Would you have any interest in a small PR that added `:export` to your .formatter.exs to enable that behavior? Thanks!

**Comment by zookzook** [comment]
PRs are welcome. If you like please provide a PR for add the :export option.
