### ISSUE TITLE
Support for multiple Mongo connections

### ISSUE THREAD

**Issue by fireproofsocks** [zookzook/elixir-mongodb-driver#163]
Wow -- great work with version 1.0.0!  It's really good to see the mix tasks!

It would be really nice to support multiple Mongo connections, rather than relying on the `:mongo` default and the `Application.get_env(:mongodb_driver, :migration, [])` override. 

I was struggling with this today trying to make our mongo interactions more similar to Ecto's.  I believe Ecto registers the name of each repo that starts and then loops over these names when issuing commands like `ecto.drop`.  I wonder if it would work to do something similar here so `mongo.drop` et al would loop over each Mongo repo.

**Comment by zookzook** [comment]
Yes, that is possible. Currently, the Mongo.Repo has no real connection to the Migration Module. But it is possible to extend the configuration, so each topologic has its own migration.

**Comment by zookzook** [comment]
Hey! Sorry for the delay. You can try out the main branch. I added support for options and multiple topologies to have full control of the migration. Check the README file.

**Comment by zookzook** [comment]
Should be fixed in version 1.0.1!
