### ISSUE TITLE
Error During Compilation

### ISSUE THREAD

**Issue by VincentRPS** [zookzook/elixir-mongodb-driver#165]
Hello! I am currently trying to use the library but keep getting this error:

```ex
== Compilation error in file lib/mongo/mongo_db_connection.ex ==
** (CompileError) lib/mongo/mongo_db_connection.ex:285: undefined function op_msg/1 (expected Mongo.MongoDBConnection to define such a function or for it to be imported, but none are available)
```

I am using Elixir 1.14 and Mix.

**Comment by zookzook** [comment]
Did you change the driver? Maybe you used another driver before (https://github.com/elixir-mongo/mongodb)? Clean the _build folder may help.

**Comment by VincentRPS** [comment]
> Did you change the driver? Maybe you used another driver before (https://github.com/elixir-mongo/mongodb)? Clean the _build folder may help.

ah seems like that fixed it, although I am encountering another error now:

```ex
19:38:56.178 [notice] Application derailed exited: Derailed.start(:normal, []) returned an error: shutdown: failed to start child: Mongo
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in anonymous fn/1 in Keyword.take/2
            (elixir 1.14.2) lib/keyword.ex:1204: anonymous fn([name: :mongo, database: "derailed", pool_size: 1, url: "mongodb://localhost:27017"]) in Keyword.take/2  
            (elixir 1.14.2) lib/keyword.ex:1204: Keyword."-take/2-lists^filter/1-1-"/2
            (mongodb_driver 1.0.0) lib/mongo/topology.ex:43: Mongo.Topology.start_link/2
            (stdlib 4.0.1) supervisor.erl:414: :supervisor.do_start_child_i/3
            (stdlib 4.0.1) supervisor.erl:400: :supervisor.do_start_child/2
            (stdlib 4.0.1) supervisor.erl:384: anonymous fn/3 in :supervisor.start_children/2
            (stdlib 4.0.1) supervisor.erl:1250: :supervisor.children_map/4
            (stdlib 4.0.1) supervisor.erl:350: :supervisor.init_children/2
```

**Comment by zookzook** [comment]
Maybe your configuration is wrong. How do you start the driver?

**Comment by VincentRPS** [comment]
> Maybe your configuration is wrong. How do you start the driver?

I start it via supervisor, although not the way it says on the docs, more like:

```ex
{Mongo, [[name: :mongo, database: "derailed", pool_size: 1, url: "mongodb://localhost:27017"]]}
```

**Comment by zookzook** [comment]
If you use a tuple as a child spec then omit the outer brackets. {Mongo, name: :mongo, database: "derailed", pool_size: 1, url: "mongodb://localhost:27017"}

**Comment by VincentRPS** [comment]
> If you use a tuple as a child spec then omit the outer brackets. {Mongo, name: :mongo, database: "derailed", pool_size: 1, url: "mongodb://localhost:27017"}

ah thanks! It seems like that fixed it
