### ISSUE TITLE
Support for Discriminators

### ISSUE THREAD

**Issue by CaseyInHaengsin** [zookzook/elixir-mongodb-driver#171]
Hello 😄 ,
I was wondering if you have plans to implement [discriminators](https://mongoosejs.com/docs/discriminators.html)?

**Comment by zookzook** [comment]
Hey,

sorry, there are no plans for discriminators so far. It follows the concept of inheritance and this does not fit good in functional programming.

**Comment by CaseyInHaengsin** [comment]
Thank you, @zookzook!
