### ISSUE TITLE
Support for update with hint option

### ISSUE THREAD

**Issue by ArthurFreitas** [zookzook/elixir-mongodb-driver#175]
Mongo 4.2 added [hint as an option for the update command](https://www.mongodb.com/docs/v4.2/reference/command/update/), but i don't think [it's currently being implemented by the lib](https://github.com/zookzook/elixir-mongodb-driver/blob/master/lib/mongo.ex#L1105).

Are there any plans for implementing this feature?

**Comment by zookzook** [comment]
I think, that should not be a problem.

**Comment by zookzook** [comment]
Feel free to use the master branch.
