### ISSUE TITLE
Mongo.update_one Error

### ISSUE THREAD

**Issue by RoboZoom** [zookzook/elixir-mongodb-driver#180]
First - thanks for all of your work keeping this repo up to date.

I'm receiving the following error when calling `Mongo.update_one`:

```
Request: POST /api/data
** (exit) an exception was raised:
    ** (ArgumentError) update only allows atomic modifiers, got: block
        (mongodb_driver 1.0.2) lib/utils.ex:54: Mongo.Utils.modifier_key/2
        (mongodb_driver 1.0.2) lib/mongo.ex:1056: Mongo.update_one/5
```
My code:
```elixir
def upsert_program(prog) do
    get_db_conn()
    |> Mongo.update_one(@collection_name, %{id: prog.id}, prog, upsert: true)
  end
```
In this case, `prog` is a map:

```elixir
 %{
  block: %{active_blocks: 0, id: "-1", trials: 0, use_blocks: false},
  created_by: "",
  created_on: "",
  ...
}
```

Any thoughts you could provide would be greatly appreciated.

**Comment by zookzook** [comment]
You forget to specify the operator of the update: "$set", "$push", "$pull" etc.

**Comment by zookzook** [comment]
If you want to replace it, then you should use the `replace_one` function.

**Comment by RoboZoom** [comment]
Thanks!

**Comment by zookzook** [comment]
By the way: the |> operator should be used only if you have more than two expressions:

```
Mongo.update_one(get_db_conn(), @collection_name, %{id: prog.id}, prog, upsert: true)
```

**Comment by RoboZoom** [comment]
Many thanks - definitely still learning elixir (and it's best practices) :)
