### ISSUE TITLE
[Q] BSON.encode crashes DBConnection

### ISSUE THREAD

**Issue by hikui** [zookzook/elixir-mongodb-driver#185]
Thanks for your great work. A question though. I noticed that if invalid data is passed to the driver, for example `%{"field" => {:error, "some error"}`, it will trigger `BSON.encode` exception, then the DBConnection will crash. Does this mean that when this happens the driver will do connect and reconnect a lot and eventually impact the performance? Would it be better if the encoding error is captured and returned to the caller?

**Comment by zookzook** [comment]
Sounds good. I will look at the implementation details and then I will come back.

**Comment by zookzook** [comment]
I changed the code to catch the exception. Feel free to check the master branch.

**Comment by hikui** [comment]
Thanks! I'll have a try

**Comment by hikui** [comment]
It works perfectly thanks
