### ISSUE TITLE
Empty list for sort gives Mongo.Error

### ISSUE THREAD

**Issue by ksmithut** [zookzook/elixir-mongodb-driver#186]
One is able to sort with a keyword list, but if you sort with an empty keyword list (aka empty list), it gives an error.

Reproduction steps:

```elixir
{:ok, conn} = Mongo.start_link(url: "mongodb://localhost:27017/my-database")
%Mongo.Stream{} = Mongo.find(conn, "test", %{}, sort: [])
```

This will create a match error:

```
** (MatchError) no match of right hand side value: {:error, %Mongo.Error{code: 14, error_labels: [], fail_command: false, host: nil, message: "Expected field sortto be of type object", not_writable_primary_or_recovering: false, resumable: false, retryable_reads: false, retryable_writes: false}}
```

I've tracked the code down to [this function](https://github.com/zookzook/elixir-mongodb-driver/blob/143773625f3abaabf15cb7848ba1029015319a51/lib/bson/encoder.ex#L103-L134) where it reduces over the list. When it's a list of key/value tuples, it will create an iodata encoded bson object, but if it's empty, the io data will be `""`. I'm not sure what the right answer is here. With elixir, you can't determine whether `[]` is meant to be an empty list or empty keyword list.

**Comment by zookzook** [comment]
Hey ksmithut!

The `:sort` keyword belongs to the option of the `find` function. First, you can just avoid specifying an empty list for the sort option. But we can extend the `filter_nils` function to handle this case (`sort: []`) as well.

```elixir
    cmd =
      [
        findAndModify: coll,
        query: filter,
        update: replacement,
        bypassDocumentValidation: opts[:bypass_document_validation],
        maxTimeMS: opts[:max_time],
        fields: opts[:projection],
        new: should_return_new(opts[:return_document]),
        sort: opts[:sort],
        upsert: opts[:upsert],
        collation: opts[:collation],
        writeConcern: write_concern
      ]
      |> filter_nils()
```
