### ISSUE TITLE
Demand research: functionality related to collection validator

### ISSUE THREAD

**Issue by v-anyukov** [zookzook/elixir-mongodb-driver#188]
MongoDB offers a pretty flexible ways for validating collection documents (https://www.mongodb.com/docs/manual/core/schema-validation/), and wouldn't it be nice to have some sort of toolkit integrated into the driver for this?

Here are a few things that could be addressed in this area:

- Functions like attach_validator, detach_validator, validate_collection, get_current_validator and so on.
- Perhaps some handy tools to convert JSON schema into a format that MongoDB can accept (https://www.mongodb.com/docs/manual/reference/operator/query/jsonSchema/#std-label-json-schema-omission).

But here's the big question: do we even need this? I mean, I genuinely don't know if anyone uses this feature at all.

**Comment by zookzook** [comment]
Personally, I don't use it. Maybe no one will use it either. So, the work would be just for the honor :-)

**Comment by zookzook** [comment]
Closing due to no response.
