### ISSUE TITLE
Cant search in nested object in mongodb by one key

### ISSUE THREAD

**Issue by MIIIG** [zookzook/elixir-mongodb-driver#190]
Here i get nil with Repo.get_by():
`[info] CMD find "contacts" [filter: [kind: "group", phones: [%{number: "1234"}]], limit: 1, batchSize: 1] db=1.1ms
[info] Sent 200 in 4ms
nil`
Here i get document with Repo.get_by(): 
`[info] CMD find "contacts" [
  filter: [
    kind: "group",
    phones: [
      %{
        description: "For work",
        number: "1234",
        type: "work"
      }
    ]
  ],
  limit: 1,
  batchSize: 1
] db=1.9ms
[info] CMD killCursors "contacts" [cursors: [#BSON.LongNumber<1655458631002899836>]] db=0.1ms
`

**Comment by MIIIG** [comment]
`def get_by(query, opts \\ []), do: Contact |> Repo.get_by(query, opts)`
phones is just map, inserted? when contact was created

**Comment by zookzook** [comment]
Both queries are different:

db.contacts.find({"phones.number": "4818"})

is not the same like

db.contacts.find({"phones": {"number": "4818"}})

**Comment by zookzook** [comment]
The last searches for the object 

{"number": "4818"}

and not for objects that contain an attribute number with the value of 4818.

**Comment by MIIIG** [comment]
but how can i find document by the nested field number? in object 
`
%{phones: 
  %{number: "4818"
}}`

**Comment by v-anyukov** [comment]
@MIIIG Your phones is an array as far as i can see. So you need a bit different approach then nested object. Check this one https://www.mongodb.com/docs/manual/tutorial/query-array-of-documents/

**Comment by zookzook** [comment]
Just use the path style like in the mongosh example:

%{"phones.number": "4818" }}

**Comment by MIIIG** [comment]
@zookzook strange thing, i tried with dot but it cant find? maybe i made some mistake? but now it works? thanks a lot!. @v-anyukov spasibo! i try this with elixir

**Comment by MIIIG** [comment]
another thing i find? i created collection contacts and

**Comment by zookzook** [comment]
Keep in mind the keyword is elixir/erlang features. The mongodb does not support those types.
```
collection "contacts" do 
  attribute :birthday, String.t()
  attribute :phones, list(any())
```
In your case I would define a document for phones and uses the embeds_many macro to like this:
````

defmodule Phone do
  @moduledoc false

  use Onsen, :collection

  document do
    attribute :code, String.t()
    attribute :number, String.t()
  end
end

...
embeds_many(:phones, Phone)
...

**Comment by MIIIG** [comment]
Thnsk, but why if i use type Integer.t() for :birthday it still works and if i create contact and define %{birthday: "13.05.1986"} in args it works?

**Comment by zookzook** [comment]
The type spec stuff is not used in the collection macro. It only creates the type spec but it does not validate or cast the type because Elixir/Erlang uses a dynamic typing model. You can use whatever you want.

**Comment by MIIIG** [comment]
Thanks a lot! Sorry, about so many questions!
how to use it `use Onsen, :collection`?
like that? - `  use ApplicationDb.Models.Contact, :collection`

**Comment by MIIIG** [comment]
i cant find how to use $elemMatch for query arrays(if I right, its only works if use clear  command to mongodb) and with embeds_many macros? then match a lot of field of the phone document i contact, but for creation in root object I need to use Phone.new() to define nil fields, if query have some fields of phone? Thanks, a lot!

**Comment by zookzook** [comment]
The "embeds_many" macro is only used to construct struct documents and provide load and dump functions for serialization. Querying the database is still up to you. So, what do you want to search with "$elemMatch"?

**Comment by MIIIG** [comment]
Owh? Thanks!  I Forget about that, it works for my purposes, but using embed documents return me full document with atom keys types, but if i puting arrays(elixir map) it returns me nested objects with string keys type, than it must be converted and returned to API

**Comment by zookzook** [comment]
You need to use the load/dump function. If you get a document from MongoDB you call the load function. This converts the string keys into atoms. The dump function should be called before sending to MongoDB.

**Comment by zookzook** [comment]
I think we can close this issue. Feel free to open a new one.
