### ISSUE TITLE
SSL Warnings

### ISSUE THREAD

**Issue by ThomasGl** [zookzook/elixir-mongodb-driver#191]
I have a basic Atlas cluster database deployed, and trying to access it even with the guidelines displayed at the end of the readme file, passing keyfile, certfile and cacertfile does no effect to make the messages stop, thus, for now I passed in the ssl_opts: [verify: :verify_none] following the httpc erlang suggestion from the erlang docs.

Is there any information on how to adjust this matter? As I believe passing the correct files should solve it. Also can I pass absolute paths for the files?

**Comment by zookzook** [comment]
What is the warning or error message?

**Comment by zookzook** [comment]
Feel free to watch this nice video: https://www.youtube.com/watch?v=0jzcPnsE4nQ

**Comment by zookzook** [comment]
Closing due to no response.
