### ISSUE TITLE
Elixir 1.15.2, otp 25.0 - bitstring specifier does not exist warnings

### ISSUE THREAD

**Issue by pradeep-in** [zookzook/elixir-mongodb-driver#193]
Getting a lot of these warnings, but seem like they could be an issue at some point. Or is it fine?

```
warning: bitstring specifier "int64" does not exist and is being expanded to "int64()", please use parentheses to remove the ambiguity
  lib/bson/encoder.ex:54: BSON.Encoder.encode/1
```

**Comment by zookzook** [comment]
I guess it is fine because these bitstring specifiers are macros. I will add the missing parentheses.

**Comment by zookzook** [comment]
The PR #195 fixes the warnings.
