### ISSUE TITLE
Setting `read_preference` for a single operation 

### ISSUE THREAD

**Issue by MarcusSky** [zookzook/elixir-mongodb-driver#194]
Hey! I'm looking to use `read_preference` for a single operation that I have to make, and I'm having a hard time understanding how to do it. In GO it would look something like:

```go
cursor, err := q.database.Collection("my-collection", &options.CollectionOptions{
    ReadPreference: readpref.SecondaryPreferred(),
}).Aggregate(ctx, mongoQuery, &options.AggregateOptions{
    AllowDiskUse: &allowDiskUse,
})
```

https://www.mongodb.com/docs/manual/reference/method/Mongo.setReadPref/#mongodb-method-Mongo.setReadPref

Can anyone help me with this?

**Comment by zookzook** [comment]
Heya,

I assume that I need to improve the documentation! For now look at the unit test to get an idea how it works:

https://github.com/zookzook/elixir-mongodb-driver/blob/master/test/mongo/read_preferences_test.exs

**Comment by MarcusSky** [comment]
thank you for your answer @zookzook! Am I safe to assume that the same applies for `Mongo.aggregate` and `Mongo.find`? I would be happy to open a PR adding these details to the documentation as well as adding tests for this!
