### ISSUE TITLE
db_connection 2.5.0

### ISSUE THREAD

**Issue by thiagomagro** [zookzook/elixir-mongodb-driver#197]
Hello guys, Im having an issue running "mix deps.get" with the newer version  of db_connection.
Is it possible to upgrade?

`Because "the lock" specifies db_connection 2.5.0 and mongodb_driver >= 0.8.2 depends on db_connection ~> 2.4.1, the lock is incompatible with mongodb_driver >= 0.8.2.
And because your app depends on the lock, mongodb_driver >= 0.8.2 is forbidden.
So, because your app depends on mongodb_driver ~> 1.0.0, version solving failed.
** (Mix) Hex dependency resolution failed`

**Comment by zookzook** [comment]
I will test it soon. In the meanwhile, you can use the `override: true` option.

**Comment by zookzook** [comment]
The mix.lock file uses 2.5.0 now.
