### ISSUE TITLE
SSL Warnings

### ISSUE THREAD

**Issue by ThomasGl** [zookzook/elixir-mongodb-driver#198]
Hi, I want to make sure I am using the correct setup for safe connection on my cluster. Which I made with Mongo Atlas, I followed a step-by-step tutorial from the official website, and I want to make the setup using a x509 certificate, which was issued by the atlas dashboard itself. I tried passing in the ssl_opts with the certfile pointing to the certfile path, yet I keep getting warning that no file was located. As I am including in screenshot. Remark: I passed also other configurations that I found in the library description: ```ssl: :tls, auth_mechanism: :x509, ssl_opts: [cipher_suite: :strong, reuse_sessions: true, secure_renegotiate: true ```
![Screenshot from 2023-08-02 16-10-48](https://github.com/zookzook/elixir-mongodb-driver/assets/56161967/626eee21-16f5-4ec9-9677-47b82a6ff281)

**Comment by zookzook** [comment]
The SSL stuff belongs to the Erlang implementation.

This might be helpful: https://youtu.be/0jzcPnsE4nQ

> I tried passing in the ssl_opts with the certfile pointing to the certfile path, yet I keep getting warning that no file was located.

Which option did you use?

**Comment by zookzook** [comment]
The error message from above says that the SSL client was not able to verify the certificate of the server, because the default configuration is not to use any trust-store. An easy solution is just to use https://hex.pm/packages/castore
and use the config:

```elixir
ssl_opts: [verify: :verify_peer, cacertfile: CAStore.file_path()]
```

**Comment by zookzook** [comment]
I tried to use the x509 auth. After all, I need to update the docs and maybe refine the workflow a bit. This is a working example. Unfortunately, the password needs to be specified, otherwise the code won't send the username. The username is important! I used the castore package for the `verify_peer` option.

```elixir
    opts = [
      url: "mongodb+srv://cluster0.xxx.mongodb.net/myFirstDatabase?authSource=%24external&retryWrites=true&w=majority",
      ssl: true,
      username: "CN=cert-user",
      password: "",
      auth_mechanism: :x509,
      ssl_opts: [
        verify: :verify_peer,
        cacertfile: to_charlist(CAStore.file_path()),
        certfile: '/path-to-cert/X509-cert-2227052404946303101.pem',
        customize_hostname_check: [
          match_fun:
            :public_key.pkix_verify_hostname_match_fun(:https)
        ]
      ]]

    Mongo.start_link(opts)
```

**Comment by ThomasGl** [comment]
Fantastic! thank you so much for your help. I just one to be sure of one thing first. If we are using a x509 from mongodb atlas. It is useless to have a username and password, so your suggestion is to use the username+password to authenticate. And pass the verify option with the "verify_none", as no x509 certificate would be necessary?

**Comment by ThomasGl** [comment]
Also, on a side note, do you have any suggestion for production setup. As in the case to have the .pem file existing on memory?

I tried using the following guideline: https://www.erlang.org/docs/17/man/ssl.html as to have it encoded to DER, and use the `:cert` option instead of the `:certfile` that requires a file path.

Yet, using it `cert: File.read!("/path/to/file.pem") |> String.trim() |> X509.Certificate.from_pem!() |> X509.Certificate.to_der()`. I used the following library to make the decode https://hexdocs.pm/x509/readme.html.

Yielded the following error:

` In state finished at tls_handshake_1_3.erl:594 generated CLIENT ALERT: Fatal - Internal Error
 badarg - {:tls_alert, {:internal_error, 'TLS client: In state finished at tls_handshake_1_3.erl:594 generated CLIENT ALERT: Fatal - Internal Error\n badarg'}}`

While using the file path itself and using the `:certfile` tag worked perfectly instead.

**Comment by zookzook** [comment]
The cert pen file contains two items:
* the certificate
* the private key

If you use the der encoded certificate directly you need to specify the private key as well:

Example: I already convert the files to der format (for example: `openssl rsa -inform pem -in key.pem -outform der -out key.der`)

```elixir
        cert: File.read!("certificate.der"),
        key: {:PrivateKeyInfo, File.read!("key.der")},
```

**Comment by ThomasGl** [comment]
Great solution.

I would also suggest adding it to the README.

By the way I found easy solution to deploy it in production without having to save anything in a physical disk.

It would be to add the following values to some key within a .env or equivalent:

```elixir
pem_file_content = File.read!("/path/to/file.pem")
[{_cert_type, pem_der, _encrypt}, {_key_type, key_der, _encrypt}] = :public_key.pem_decode(pem_file_content)
pem_encoded = Base.encode64(pem_der)
key_encoded = Base.encode64(key_der)
```

Then save the pem_encoded to some key as well as the key_encoded.

And use them as follows in the ssl_opts

```elixir
cert: Base.decode64!(pem_encoded),
key: {:PrivateKeyInfo, Base.decode64!(key_encoded)}        
```
