### ISSUE TITLE
1.2.0 release did not push to hex.pm

### ISSUE THREAD

**Issue by ksmithut** [zookzook/elixir-mongodb-driver#203]
Looking at the [release action](https://github.com/zookzook/elixir-mongodb-driver/actions/runs/6093148851/job/16532339266) it looks like it skipped the push to hex.pm

**Comment by ksmithut** [comment]
@zookzook It looks like they changed the output from `release_created` to `releases_created` [*source](https://github.com/google-github-actions/release-please-action#outputs). I believe changing [these lines](https://github.com/zookzook/elixir-mongodb-driver/blob/4e4397b8d5bca8103a3fd10d93f7290458747e7d/.github/workflows/release-please.yml#L23-L32) to look at `releases_created` instead of `release_created`, then it should work going forward.

**Comment by ksmithut** [comment]
Oh, but the rest of their documentation uses `release_created`. Maybe that's not it, or their documentation is incorrect. In either case, the 1.2.0 release is not on hex.pm yet.

**Comment by zookzook** [comment]
Thanks for your hint. I think the id was missing. I checked the configuration of another project and there was an "id". Maybe next time it will work better. I pushed the version 1.2.0 to hex.pm!

**Comment by ksmithut** [comment]
Thank you!
