### ISSUE TITLE
In GridFs, allow assigning a custom `_id` to documents in `files` collection

### ISSUE THREAD

**Issue by aniruddhasd** [zookzook/elixir-mongodb-driver#216]
Hello!
Currently, when uploading a new file via GridFs there is no option to assign the `_id` field of the document to be inserted into the `files` collection. It is generated through `Mongo.object_id()`.
```elixir
  @doc """
  Creates a new upload stream to insert a file into the grid-fs.
  """
  @spec new(Bucket.t(), String.t(), BSON.document() | nil) :: UploadStream.t()
  def new(bucket, filename, metadata \\ nil) do
    %UploadStream{bucket: bucket, filename: filename, id: Mongo.object_id(), metadata: metadata}
  end
```
Request: Allow passing an optional file_id param

**Comment by zookzook** [comment]
I close this because the PR is merged.
