### ISSUE TITLE
Support MongoDB v7

### ISSUE THREAD

**Issue by stiang** [zookzook/elixir-mongodb-driver#233]
I have a client that wants to upgrade their Atlas Cluster to MongoDB v7, but I’ve asked them to wait until this driver officially supports it. They are of the opinion that there aren’t any breaking changes (relevant for us) in v7, so it will probably work just fine to use the current driver, but I am quite skeptical.

Are there any plans to support v7?

**Comment by zookzook** [comment]
I believe, there is no much difference from the driver's perspective. You can just use it with MongoDB 7. On my local machine I use 7 already.

**Comment by stiang** [comment]
OK, that’s good to know - thanks! In that case the issue can be closed as far as I am concerned, but do you maybe want to keep it open to track progress on officially supporting v7 at some point?

**Comment by zookzook** [comment]
We can keep it open to remember me to check if something is new. I have a similar issue for MongoDB 6, but didn't find the time to evaluate if there are changes for the driver. :-)

**Comment by mweidner037** [comment]
For what it's worth, after switching mongodb_ecto to use this driver (v1.4.0), we were able to add MongoDB 7.0 to the CI tests without any issues: https://github.com/elixir-mongo/mongodb_ecto/blob/04ce48dfc69c06b49d02130d48ae1a236360100a/.github/workflows/ci.yml#L39

**Comment by scottmessinger** [comment]
@zookzook I think this issue can be closed? With Mongo 8 out, there should probably be a new issue for Mongo 8.
