### ISSUE TITLE
@spec on find_one_and_update/4 says the function can return `{:ok, nil}`

### ISSUE THREAD

**Issue by PsychicPlatypus** [zookzook/elixir-mongodb-driver#249]
`find_one_and_update/4` has the following `@spec`:
```ex
...
@spec find_one_and_update(
          GenServer.server(),
          collection,
          BSON.document(),
          BSON.document(),
          Keyword.t()
        ) :: result(Mongo.FindAndModifyResult.t()) | {:ok, nil} # <~ here
  def find_one_and_update(topology_pid, coll, filter, update, opts \\ []) do
    _ = modifier_docs(update, :update)
...
```

Previously this returned `nil` if the document couldn't be found, but now upon not finding the doc the function returns:
```ex
{:ok,
 %Mongo.FindAndModifyResult{
   value: nil,
   matched_count: 0,
   upserted_id: nil,
   updated_existing: false
 }}
```

Is there any way it can return `{:ok, nil}` or is the spec incorrect?

**Comment by zookzook** [comment]
The spec is wrong. It will always return the `%Mongo.FindAndModifyResult{}' struct. It was changed to support the mongo ecto package.

**Comment by PsychicPlatypus** [comment]
I just looked through the code again (you were quicker than me), and found it will never return `{:ok, nil}`
```ex
with {:ok, doc} <- issue_command(topology_pid, cmd, :write, opts) do
      {:ok,
       %Mongo.FindAndModifyResult{
         value: doc["value"],
         matched_count: doc["lastErrorObject"]["n"],
         updated_existing: doc["lastErrorObject"]["updatedExisting"],
         upserted_id: doc["lastErrorObject"]["upserted"]
       }}
    end
```

**Comment by PsychicPlatypus** [comment]
Another minor thing is that functions with the "result" type will never actually return `:ok`:
```ex
@type result(t) :: :ok | {:ok, t} | {:error, Mongo.Error.t()} | {:error, Mongo.WriteError.t()}
```

**Comment by zookzook** [comment]
Thanks for reporting. To be honest, I never pay much attention to the specifications. It is therefore possible that some specs are outdated and no longer correct.

**Comment by PsychicPlatypus** [comment]
Another very minor thing is that `@type initial_type :: :unknown | :single | :replica_set_no_primary | :sharded` is never used
