### ISSUE TITLE
Support Mongo v8

### ISSUE THREAD

**Issue by scottmessinger** [zookzook/elixir-mongodb-driver#253]

**Comment by scottmessinger** [comment]
Looks like the tests pass, so the Readme can probably be updated? #254

**Comment by zookzook** [comment]
Thank you! It is merged.

**Comment by basmoura** [comment]
any plans to generate the release with this support for mongo 8 update?

**Comment by scottmessinger** [comment]
@basmoura It already works with Mongo 8 -- the only change was updating the readme and adding it to the CI. You can use it now at its current release.
