### ISSUE TITLE
Aggregate indexStats no response

### ISSUE THREAD

**Issue by MileaRobertStefan** [zookzook/elixir-mongodb-driver#259]
I'm trying to do indexStats but all I  get an empty array.

I have checked with mongo compass and indexStats does work as expected.
I'm on MongoDB 1.4.1.
```
    stats_pipeline = [%{"$indexStats" => %{}}]

    Mongo.aggregate(topology_pid, coll, stats_pipeline) |> Enum.map(fn elem -> elem end)
```

Am I doing something wrong?

**Comment by zookzook** [comment]
The aggregate function returns a stream. `|> Enum.to_list()` may helps.

**Comment by MileaRobertStefan** [comment]
I've just updated the code snippet to include that as well.

**Comment by zookzook** [comment]
Yes, it works for me.

**Comment by zookzook** [comment]
Maybe your account used by your Elixir app doesn't have the permissions.

**Comment by MileaRobertStefan** [comment]
In this case there should be an error right?

**Comment by zookzook** [comment]
>In this case there should be an error right? I do get [ ] as a response.

Never tried :-)

**Comment by MileaRobertStefan** [comment]
I can confirm the top, and collection are correct, run a count and worked as expected.

**Comment by zookzook** [comment]
I have checked the command running on my local instance and it works.

**Comment by MileaRobertStefan** [comment]
I'm closing this because it looks like a setup issue on my end.
