### ISSUE TITLE
Crash calling wire_version/1 and limits/1 functions

### ISSUE THREAD

**Issue by ja-jimenez** [zookzook/elixir-mongodb-driver#31]
Hi! 

First of all, congratulations on your work. 

I'm using the driver to connect a mongodb  4.2.1 version. When I try to call the **wire_version/1** and **limits/1** functions I get a _FunctionClauseError_ with the following message:

> ** (FunctionClauseError) no function clause matching in Mongo.Topology.handle_info/2

The code to reproduce this error is as follow:

```elixir
{:ok, mongo_client} = Mongo.start_link url: "mongodb://127.0.0.1:27017/test"
0 = Mongo.count_documents! mongo_client, "empty_collection", nil   # This work fine
Mongo.wire_version mongo_client    # This throws the exception, limits/1 function too.

```
Regards!

**Comment by zookzook** [comment]
I think, I need to clarify the api here. You need to call the function with a connection pid. 
```elixir

{:ok, session} = Mongo.Session.start_session(mongo_client, :read, [])
connection = Mongo.Session.connection(session)
Mongo.limits(connection)
{:ok,
 %{
   compression: nil,
   logical_session_timeout_minutes: 30,
   max_bson_object_size: 16777216,
   max_message_size_bytes: 48000000,
   max_write_batch_size: 100000,
   read_only: false
 }}
Mongo.Session.end_session(mongo_client, session)
```

**Comment by ja-jimenez** [comment]
Ups, sorry, I had not realized that the parameters were different.

Thanks!

**Comment by zookzook** [comment]
No problem. I will refactor the api to make it cleaner.
