### ISSUE TITLE
Community Supported Drivers Reference

### ISSUE THREAD

**Issue by Fudoshiki** [zookzook/elixir-mongodb-driver#32]
Hello. Your work is great
I opened PR to add driver to https://docs.mongodb.com/ecosystem/drivers/community-supported-drivers

https://github.com/mongodb/docs-ecosystem/pull/571

**Comment by zookzook** [comment]
Thank you. Maybe you have more luck than me:

https://github.com/mongodb/docs-ecosystem/pull/492

:stuck_out_tongue_winking_eye:
