### ISSUE TITLE
Merge back into ankhers/mongodb?

### ISSUE THREAD

**Issue by scottmessinger** [zookzook/elixir-mongodb-driver#36]
Hi! This looks great and some really fantastic additions to what @ankhers has done. Any interest in trying to merge the changes back in? I'd just hate for work to be split across two mongo drivers when the work appears quite complementary.

**Comment by zookzook** [comment]
I currently have no intentions to merge the changes. I did refactor a lot of things so merging will be very complex. Now I'm able to merge PR as quickly as possible.

**Comment by scottmessinger** [comment]
I think I communicated the wrong thing -- by "merging", I didn't mean the mechanism of merging -- for argument, let's say we opted for your changes since you forked it. If you have any interest in being a core contributor of the main repo, it would be awesome to see if @ankhers would be interested in helping making that happen. I'm interested in seeing if there's anything that could be done to combine efforts! 

It sounds like you're main concern is you weren't able to merge in changes to the main repo. That's makes perfect sense and it sounds like having the commit bit on the main repo would address that for you. Is that right? 

Based on @ankhers's comments on issues, it seems he doesn't have as much time for the project as he wishes he did, so I wonder if he might be interested in having someone else contribute and merge in PRs. Have you gotten a chance to reach out to @ankhers  and talk about possibilities?

**Comment by zookzook** [comment]
> Have you gotten a chance to reach out to @ankhers and talk about possibilities?
No, I have not. 

Currently I see no reason to merge both repositories together and to become a core committer, because I am already a core committer in this repository :-).

I know, of course, that one driver is more practical than two. You have to choose a driver. Maybe that will change sometime in the future.
