### ISSUE TITLE
Shards support?

### ISSUE THREAD

**Issue by AlexKovalevych** [zookzook/elixir-mongodb-driver#39]
Thank you for your library, but do you plan to support shards? According to this code https://github.com/zookzook/elixir-mongodb-driver/blob/master/lib/mongo/topology_description.ex#L80 it fails when connecting to sharded mongo (trying to iterate a tuple):

```
(Protocol.UndefinedError) protocol Enumerable not implemented for {[...
```

**Comment by zookzook** [comment]
I think this kind of deployment has never been tested before. I will try to set up a sharded cluster to reproduce the error and then I will fix it.

**Comment by zookzook** [comment]
Could you provide the complete error message (without any sensitive data)?

**Comment by zookzook** [comment]
I'm able to reproduce the error message. Therefore I should fix it.

**Comment by zookzook** [comment]
Maybe you can use the current master branch to see if the fix is working for your deployment. In this case I will provide a new release.

**Comment by AlexKovalevych** [comment]
It works, thank you!
