### ISSUE TITLE
GridFS

### ISSUE THREAD

**Issue by dmarko484** [zookzook/elixir-mongodb-driver#40]
Are there any plans for supporting GridFS? Thanks

**Comment by zookzook** [comment]
Please check 

* https://github.com/zookzook/elixir-mongodb-driver/tree/master/test/mongo/grid_fs
* https://hexdocs.pm/mongodb_driver/0.6.4/Mongo.GridFs.Bucket.html#content

**Comment by zookzook** [comment]
Added some information about GridFS:

https://github.com/zookzook/elixir-mongodb-driver#gridfs
