### ISSUE TITLE
UUID support

### ISSUE THREAD

**Issue by fairbairn** [zookzook/elixir-mongodb-driver#43]
It would be nice if the BSON interface would support the UUID syntax/encoder/decoder in mongo.

https://docs.mongodb.com/manual/reference/method/UUID/

**Comment by zookzook** [comment]
See `Mongo.uuid/0`, `Mongo.uuid/1` and `Mongo.uuid!/1'

**Comment by zookzook** [comment]
Any comments? Maybe feedback?
