### ISSUE TITLE
Include error handling logic for transactions

### ISSUE THREAD

**Issue by ja-jimenez** [zookzook/elixir-mongodb-driver#47]
Hello.

Lately I am testing the transactions feature of this driver, and I have seen that it doesn't follow the error handling logic like it is commented in this [link](https://docs.mongodb.com/manual/core/transactions-in-applications/index.html). 

The problem is that right now the driver doesn't return to the app errors labeled, so we cannot check if it include the **TransientTransactionError** or **UnknownTransactionCommitResult** label to retry the transaction.

Secondly, maybe the function Session.with_transaction(fn) could be implemented like a [Callback API](https://docs.mongodb.com/manual/core/transactions-in-applications/index.html#callback-api).

Regards.

**Comment by zookzook** [comment]
You can use the git repository to check the `errorFlags`. In the meantime I will work on the event system. So it will take some time for the next release.

**Comment by zookzook** [comment]
The transaction api returns an error. See `Mongo.TransactionRetriesTest` test case:

```elixir
 {:ok, session} = Session.start_session(top, :write, [])
    assert :ok = Session.start_transaction(session)

    assert {:ok, _} = Mongo.insert_one(top, coll, %{name: "Greta"}, session: session)

    cmd = [
      configureFailPoint: "failCommand",
      mode: [times: 1],
      data: [errorCode: 3, failCommands: ["commitTransaction"]]
    ]

    {:ok, _doc} = Mongo.admin_command(top, cmd)

    {:error, %Mongo.Error{}} = Session.commit_transaction(session)

    assert :ok == Session.abort_transaction(session)
    assert :ok == Session.end_session(top, session)
```

Currently the driver will retry the commit in case of `UnknownTransactionCommitResult` error labels.

**Comment by zookzook** [comment]
In case of `TransientTransactionError` or `UnknownTransactionCommitResult` the function will retry the whole transaction or  the commit of the transaction. You can specify a timeout (`:transaction_retry_timeout_s`) to limit the time of repeating.  The default value is 120 seconds.
