### ISSUE TITLE
Request: allow sorting in find_one

### ISSUE THREAD

**Issue by leolara** [zookzook/elixir-mongodb-driver#50]
Sometimes sorting in find_one is useful, perhaps I need to find the first in a collection using certain sorting.

Currently I need to do a normal find using limit 1, and then extract from the resulting list.

**Comment by zookzook** [comment]
Yes, that's the way that `find_one` works. But I can remove the `Keyword.delete(:sort)` expression.

**Comment by leolara** [comment]
Yes, please, that way I can use find_one to get the first or the last in an
ordering
