### ISSUE TITLE
Add support for client side field level encryption

### ISSUE THREAD

**Issue by zookzook** [zookzook/elixir-mongodb-driver#56]
https://docs.mongodb.com/drivers/use-cases/client-side-field-level-encryption-guide

**Comment by p-mongo** [comment]
FLE requires interfacing with libmongocrypt which is written in C. Ruby does this via FFI, some other languages use FFI also and others have native bindings. I see https://github.com/joshnuss/elixir-ffi but the note there says not to use it.

**Comment by zookzook** [comment]
Since the Client-Side Field Level Encryption feature is only available for the enterprise edition, I close the issue. Feel free to reopen the issue.
