### ISSUE TITLE
Sort order not respected

### ISSUE THREAD

**Issue by floriandotorg** [zookzook/elixir-mongodb-driver#58]
Hey, first thanks for this awesome package!

We've encountered a bug. In JS/Mongo maps have an order:
`{ a: 1, b: 2 } !== { b: 2, a: 1 }`

This is not the case in Elixir:
`%{ a: 1, b: 2 } == %{ b: 2, a: 1 }`

This leads to a problem with sorting since with Mongo the order of the sorting map is important:
`Mongo.find(:mongo, "collection", filter, sort: %{ fieldA: 1, fieldB: -1 })` should yield different results than `Mongo.find(:mongo, "collection", filter, sort: %{ fieldB: -1, fieldA: 1 })`, but it doesn't.

**Steps to reproduce**:
Execute two find queries:
`Mongo.find(:mongo, "collection", filter, sort: %{ fieldA: 1, fieldB: -1 })` 
`Mongo.find(:mongo, "collection", filter, sort: %{ fieldB: -1, fieldA: 1 })`

**Current behavior**:
Order  of results is the same.

**Desired behavior**:
Order of results differs.

Might you have a workaround or can fix this? Thanks.

**Comment by zookzook** [comment]
Instead of using maps you can use keyword list as well, then the order of the fields is preserved:

{code}
iex(2)> [a: 1, b: 2] == [b: 2, a: 1]
false
iex(3)> [b: 2, a: 1] == [b: 2, a: 1]
true
{code}

{code}
Mongo.find(:mongo, "collection", filter, sort: [fieldB: -1, fieldA: 1])
{code}

**Comment by floriandotorg** [comment]
Awesome, thanks for the prompt answer!
