### ISSUE TITLE
mongo_db_connection.ex:250: undefined function op_msg/1

### ISSUE THREAD

**Issue by danyflorez** [zookzook/elixir-mongodb-driver#59]
Hi, Thanks for working hard on this library, 

I'm getting the following error when adding the library to my project:

== Compilation error in file lib/mongo/mongo_db_connection.ex ==
** (CompileError) lib/mongo/mongo_db_connection.ex:250: undefined function op_msg/1
    (elixir 1.10.3) src/elixir_locals.erl:114: anonymous fn/3 in :elixir_locals.ensure_no_undefined_local/3

Do you know what can I do to solve it?

**Comment by zookzook** [comment]
I need more information:

What version do you use?
```
elixir -v
Erlang/OTP 22 [erts-10.4.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.9.1 (compiled with Erlang/OTP 22)
```

If I compile the driver, I have no problems:

```
==> mongodb_driver
Compiling 39 files (.ex)
Generated mongodb_driver app
```

**Comment by zookzook** [comment]
Even with the newest version of elixir and OTP 23 I get no compiler errors:

```
elixir -v
Erlang/OTP 23 [erts-11.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.10.3 (compiled with Erlang/OTP 22)
```

**Comment by danyflorez** [comment]
elixir -v
Erlang/OTP 22 [erts-10.7.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.10.3 (compiled with Erlang/OTP 22)

When I compile is fine is when I run "mix test" that this error shows up

**Comment by zookzook** [comment]
`Mongo.Messages` defines is `op_msg` record:

```elixir
defrecord  :op_msg, [:flags, :sections]
```

so...maybe there is an old version of `Mongo.Messages` used. Try to clean all the builds and try again.

**Comment by danyflorez** [comment]
It worked! thanks
