### ISSUE TITLE
Transactions on different databases

### ISSUE THREAD

**Issue by ja-jimenez** [zookzook/elixir-mongodb-driver#64]
Hi!

In MongoDB transactions [doc](https://docs.mongodb.com/manual/core/transactions-operations/), it says that it's possible to make CRUD operations inside a transaction on different collections, and this collections can be in different database.

Can we get this behavior using this driver? I'm trying to test this behavior, but when we create a topology we must bind it to one database, so the session (and transaction) are bond to that database, and I don't know how to write in other collections stored in other database, or if it is possible to do this.

Regards.

**Comment by zookzook** [comment]
You can use the `:database` option to select the database. Doing so, maybe you get transaction on different database without any code changes. I have not tested this situation, but it would be interesting, if it already works. In this case, I would add some unit tests.

**Comment by ja-jimenez** [comment]
Ok, thanks.

I am going to test it and give you feedback.

**Comment by ja-jimenez** [comment]
Hi!

I have tested it and it looks like it is working. I have used this simple code to test it:

```elixir
Mongo.Session.with_transaction(
        topology,
        fn opts ->
          %{"count" => count} = Mongo.find_one(topology, @test_transaction_coll, [_id: 1], opts)
          with {:ok, %Mongo.UpdateResult{}} <- Mongo.update_one(
            topology,
            @test_transaction_coll,
            [_id: 1],
            [
              "$set": [
                count: (count + 1)
              ]
            ],
            opts
          ),
               {:ok, %Mongo.UpdateResult{}} <- Mongo.update_one(
                 topology,
                 @test_transaction_coll,
                 [_id: 1],
                 [
                   "$push": [
                     numbers: (count + 1)
                   ]
                 ],
                 Keyword.merge(opts, database: @test_transaction_db_2)
               ) do
            {:ok, :ok}
          else
            error ->
              Logger.debug("Transaction id #{id} error: #{inspect(error)}")
              error
          end
        end
      )
```
This code is called from different processes concurrently and I am getting the expected result. I initialize the database with the following info:

- Database test_1 - Collection test:
```json
{
  "_id": 1,
  "count": 0
}
```
- Database test_2 - Collection test:
```json
{
  "_id": 1,
  "numbers": []
}
```

Regards.

**Comment by zookzook** [comment]
I added a new unit test for transaction with multiple databases. Thank you for the hint.
