### ISSUE TITLE
telemetry support

### ISSUE THREAD

**Issue by AlexKovalevych** [zookzook/elixir-mongodb-driver#65]
Any plans on that? Curious why Registry approach was chosen over telemetry for events logging. Also as far as i can tell it's not possible right now to use things like [opentelemetry](https://github.com/open-telemetry/opentelemetry-erlang-api) for nested spans (e.g.: for query tracing)

**Comment by zookzook** [comment]
I'm sorry, currently I have no plans to use open telemetry. But maybe in the future, I would add telemetry support. The Registry approach is currently used for ExUnits tests, so I can trace some events in case of retry-reads and retry-writes workflows.

**Comment by zookzook** [comment]
I added support for telemetry and logging. Feel free to check the master branch.
