### ISSUE TITLE
Consider write some examples or documentation to create Indexes

### ISSUE THREAD

**Issue by dbuos** [zookzook/elixir-mongodb-driver#72]
It is not clear how an index can be created, it would be nice to have an example of how to do it.

best regards.

**Comment by zookzook** [comment]
Example:

```elixir
indexes =  [[key: [files_id: 1, n: 1], name: "files_n_index", unique: true]]
Mongo.create_indexes(topology_pid, "my_collection", indexes, opts)
```

If you look at the specification of the function, you see two parameters
```elixir
def create_indexes(topology_pid, coll, indexes, opts \\ [])
```

The function creates a command:

```elixir
[createIndexes: coll, indexes: indexes]
```

For all details of the `createIndexes` command look at 
https://docs.mongodb.com/manual/reference/command/createIndexes/#dbcmd.createIndexes

**Comment by zookzook** [comment]
I added some documentation to create indexes in the readme file.
