### ISSUE TITLE
GenServer.call timeout not captured

### ISSUE THREAD

**Issue by fairbairn** [zookzook/elixir-mongodb-driver#73]
Reproduce..

```
{:mongodb_driver, "~> 0.7.0"},
> db.version()
4.2.8
Elixir 1.10.3
```
Start up mongo server
`brew services start mongodb-community`

Start up Mongo instance

```
children =
          [
            worker(Mongo, [db_params])
          ]
      end
    opts = [strategy: :one_for_one, name: PVApp.Supervisor]
    pid = Supervisor.start_link(children, opts)
```

Shutdown mongo server
`brew services stop mongodb-community`

Perform mongo.find() operation...

```
** (exit) exited in: GenServer.call(:mongo, {:checkout_session, :read, :implicit, [name: :mongo, pool: nil]}, 5000)
    ** (EXIT) time out
```

It can also create this scenario...
```
** (stop) exited in: GenServer.call(:mongo, {:checkout_session, :write, :implicit, [name: :mongo, pool: nil, write_counter: 1]}, 5000)
    ** (EXIT) time out
    (elixir 1.10.3) lib/gen_server.ex:1023: GenServer.call/3
    (mongodb_driver 0.7.0) lib/mongo/session.ex:170: Mongo.Session.start_implicit_session/3
(stdlib 3.12) gen.erl:167: :gen.do_call/4
    (elixir 1.10.3) lib/gen_server.ex:1020: GenServer.call/3
    (mongodb_driver 0.7.0) lib/mongo/session.ex:170: Mongo.Session.start_implicit_session/3
    (mongodb_driver 0.7.0) lib/mongo/stream.ex:17: Mongo.Stream.new/3
    (mongodb_driver 0.7.0) lib/mongo.ex:676: Mongo.find/4
```

Culprit is that this call is fired, using the default timeout of 5000...pretty standard...

```
def checkout_session(pid, cmd_type, type, opts \\ []) do
    GenServer.call(pid, {:checkout_session, cmd_type, type, opts})
end
```

The underlying operations are still pending (TCP connection waiting for connect I would presume)...
GenServer times out before TCP connection attempt returns..
Not captured, GenServer exits, crashes process (of course our Supervisor recovers, but our .find() call doesn't know what happened)

The desired result is that we would get some kind of error response on the .find() call in the expected {:error, _} format, hopefully indicating that a downstream timeout occurred...

{:error, ...} = Mongo.find()..

but we can't capture the timeout scenario.  

We tried altering our pool_timeout and connect_timeout settings as opts going into the initial Mongo setup, but that didn't seem to have any effect.  My guess is the cursor timeout plays a role.

Any suggestions on how we can properly handle this condition?

**Comment by zookzook** [comment]
Sorry, for the long delay. If you look into the `handle_call` function for checkout, you see, that in your case :empty is returned from `TopologyDescription.select_servers` (I guess) and in this case the driver put the pid into list called `waiting_pids`. So far so good. But this does not help, because of the default timeout in `GenServer.call`. 

```elixir
  def handle_call({:checkout_session, cmd_type, type, opts}, from, %{:topology => topology, :waiting_pids => waiting} = state) do

    case TopologyDescription.select_servers(topology, cmd_type, opts) do
      :empty ->
        Mongo.Events.notify(%ServerSelectionEmptyEvent{action: :checkout_session, cmd_type: cmd_type, topology: topology, opts: opts})
        {:noreply, %{state | waiting_pids: [from | waiting]}} ## no servers available, wait for connection

```

My first idea would be to add a timeout option for the GenServer.call and catch the exception and map it an error. Would this help according to your specified use case? I guess, the checkout call only times out, if no connection exists.
