### ISSUE TITLE
Upgrade :db_connection to remove System.stacktrace/0 warning, is it possible?

### ISSUE THREAD

**Issue by vukanac** [zookzook/elixir-mongodb-driver#80]
```
warning: System.stacktrace/0 is deprecated, use __STACKTRACE__ instead
   lib/db_connection/connection.ex:72

warning: System.stacktrace/0 is deprecated, use __STACKTRACE__ instead
   lib/connection.ex:429
```

https://github.com/elixir-ecto/db_connection/issues/225#issue-720840851

`:db_connection ~> 2.3`

Btw,
the `connection` - [https://github.com/fishcakez/connection](https://github.com/fishcakez/connection)
is redirected to
the `db_connection` - [https://github.com/elixir-ecto/db_connection](https://github.com/elixir-ecto/db_connection).

**Comment by zookzook** [comment]
PR approved. Thank you!
