### ISSUE TITLE
@spec incorrect for create_indexes

### ISSUE THREAD

**Issue by samlotti** [zookzook/elixir-mongodb-driver#86]
The spec and comment specify a keyword list, however its a list of keyword lists.
The tooling (vscode) says 
 'Function after_startup/0 has no local return.ElixirLS Dialyze' for my function and
 'The function call will not succeed'

If I correct the code to get rid of warnings, then the code doesn't work.

**Working code  But anaylzer says The function call will not succeed :**
list_of_keyword = [ [key: [cryptohash: 1], name: "cryptohash_index", unique: true] ]
Mongo.create_indexes(:mongo, @collection, list_of_keyword )

**No warnings, but doesn't work**
keyword = [key: [cryptohash: 1], name: "cryptohash_index", unique: true] 
Mongo.create_indexes(:mongo, @collection, keyword )

Spec in mongo.ex
@spec create_indexes(GenServer.server, String.t, Keyword.t, Keyword.t) :: :ok | {:error, Mongo.Error.t}

**Comment by zookzook** [comment]
Hi samlotti,

I'm sorry, but I don't care about specs and the Dialyzer. It is maybe a nice feature, but it does not really help and the compiler is ignoring it. So, let me quote Dave Thomas:

> Ultimately, dialyzer is a tool, not a test of your coding chops. Use it as such, but don't waste time adding specs to get a gold star.

But you can create a PR and I will merge it.

**Comment by samlotti** [comment]
Looks like its been fixed in the latest master branch.  The comment for the function also now reflects the list.
