### ISSUE TITLE
Undefined or private type spec?

### ISSUE THREAD

**Issue by bryansray** [zookzook/elixir-mongodb-driver#87]
I see some examples in this repository as well as the yildun.collection repository where you specify `BSON.ObjectId.t()` as a type. However, when It ry to use it ... 

`embeds_many :students, BSON.ObjectId.t()`

I'm receiving this error message:

```
 (UndefinedFunctionError) function BSON.ObjectId.t/0 is undefined or private
    (mongodb_driver 0.7.1) BSON.ObjectId.t()
    lib/photon/instructional/cohort.ex:27: (module)
    (stdlib 3.14) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir 1.11.3) lib/kernel/parallel_compiler.ex:314: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

Am I missing something? I see the type spec defined. But for the life of me I can't seem to use it.

**Comment by bryansray** [comment]
Hmmm ... apparently something to do with the yildun library. You can't use `BSON.ObjectId.t()` with the `embeds_many`. But it looks like i can simply use the `attribute` apologies for placing this in the wrong repository. I think I've solved this.

I am partially curious why you can't `embeds_many` on `BSON.ObjectId` structs though? I'm guessing something to do with the macro's that generate the code? Would love to know more.

**Comment by zookzook** [comment]
> I am partially curious why you can't embeds_many on BSON.ObjectId structs though? I'm guessing something to do with the macro's that generate the code? Would love to know more.

I think, you need to remove the type spec stuff:

```elixir
embeds_many :students, BSON.ObjectId
```

The embeds_many macro expects that the second parameter is a module:

```elixir
  defmacro embeds_many(name, mod, opts \\ []) do
    quote do
      type = unquote(Macro.escape({{:., [], [mod, :t]}, [], []}))
      Collection.__embeds_many__(__MODULE__, unquote(name), unquote(mod), type, unquote(opts))
    end
  end
```
