### ISSUE TITLE
The `@spec` for function `find/4` does not cover error results

### ISSUE THREAD

**Issue by vukanac** [zookzook/elixir-mongodb-driver#88]
The function `find/4` returns `cursor` but also can return `{:error, error}`.
The spec does not cover error results.

https://github.com/zookzook/elixir-mongodb-driver/blob/master/lib/mongo.ex#L639

The `{:error, error}` from [Mongo.Stream.new/3](https://github.com/zookzook/elixir-mongodb-driver/blob/master/lib/mongo/stream.ex#L12)

can be:
- `{:error, term()}` from `Session.start_implicit_session`
- `{:error, Mongo.Error.t}` from `Mongo.exec_command_session`
- `{:error, Mongo.Error.exception("...")}`

What would be for you narrowest type for error?

**Comment by zookzook** [comment]
Hi vukanac,

I'm sorry, but I don't care about specs and the Dialyzer. It is maybe a nice feature, but it does not really help and the compiler is ignoring it. So, let me quote Dave Thomas:

> Ultimately, dialyzer is a tool, not a test of your coding chops. Use it as such, but don't waste time adding specs to get a gold star.

**Comment by vukanac** [comment]
Hi @zookzook,

I really like your lib and with it you are helping the community a lot.
A do also like to check types with dialyzer and I assume I am not the only one here.
With current state I have to choose one or the other or to think of work arrounds.
I would like to use both.

I was checking what are possibilities how to keep the both of them:
* A one option is a small update of specs,
* the other is to remove specs for the function to enable us to deal with it,
* the worst option would be to make a fork.

The first option would be the better and the easier.

Would you consider accepting a small update I can provide, to update specs for `find` function?

```
@spec find(GenServer.server, collection, BSON.document, Keyword.t) :: cursor | {:error, term()}
```
This would cover all cases from description.

Thanks,
@vukanac

**Comment by zookzook** [comment]
Hi vukanac,

of course. Please provide PR and I will merge it. And if you like, I can provide a new release as well.

**Comment by vukanac** [comment]
Hi @zookzook ,

PR created, please take a look.

Thanks!

**Comment by vukanac** [comment]
I am closing this, as PR is merged. Thanks!
