### ISSUE TITLE
undefined function op_msg/1

### ISSUE THREAD

**Issue by scottmessinger** [zookzook/elixir-mongodb-driver#92]
Hi! I'm trying to integrate this driver into the mongodb_ecto adapter and when I try to start up the test suite for mongodb_ecto, I get a compile error before anything can run.

```
== Compilation error in file lib/mongo/mongo_db_connection.ex ==
** (CompileError) lib/mongo/mongo_db_connection.ex:250: undefined function op_msg/1
    (elixir 1.11.3) src/elixir_locals.erl:114: anonymous fn/3 in :elixir_locals.ensure_no_undefined_local/3
    (stdlib 3.14) erl_eval.erl:680: :erl_eval.do_apply/6
```

It appears `op_msg` is called from [here](https://github.com/zookzook/elixir-mongodb-driver/blob/2b10649447680db67a3c4ec67ece9638922e6962/lib/mongo/mongo_db_connection.ex#L250) but never declared anywhere. 

Any idea why I'm running into this error?

**Comment by zookzook** [comment]
Sorry, but I don't know, what you doing to integrate the driver with ecto. I close this issue, because it is not related to the driver. In other case feel free to create a new issue.

**Comment by joeapearson** [comment]
@scottmessinger I was able to fix this using `mix deps.clean`.  I think the problem occurs when you swap out the original `mongodb` with `mongodb_driver`.

**Comment by scottmessinger** [comment]
@joeapearson Thanks! I wondered if that could be related. I haven't gotten a chance to go back and try this again, but it's good to know it works.
