### ISSUE TITLE
Write timeouts

### ISSUE THREAD

**Issue by toddholmberg** [zookzook/elixir-mongodb-driver#97]
Hello. I am consistently getting the following error:

`GenServer.call(:mongo, {:checkout_session, :write, :implicit, [continue_on_error: true, w: 2, wtimeout: 10000, write_counter: 1]}, 5000)`

My app is using connection pooling. It appears that the `Genserver.call` is timing out, hence the `5000` at the end of the call. Is it possible to increase that timeout value?

**Comment by zookzook** [comment]
Hey!

I guess it should be easy to pipe some options to the GenServer call to increase the default timeout, so you should be able to specified a custom timeout value. 

But maybe it is a good idea to increase the connection pool for the moment. I guess, the pool is exhausted and therefore the process must wait.

**Comment by zookzook** [comment]
I added a new option in the PR #98, so check the master branch, if the solution works for our case. I will provide a new release.

**Comment by toddholmberg** [comment]
@zookzook 
This is exactly what I needed. I can't increase the connection pool right now due to connection limits that conflict with our scaling needs. Adding this timeout while we work this out is a great benefit. Thank you for getting to this so quickly.

**Comment by zookzook** [comment]
I have published a new version.
