### ISSUE TITLE
Logging queries with application name

### ISSUE THREAD

**Issue by joaovbibiano** [zookzook/elixir-mongodb-driver#99]
Hi!

I searched on the documentation but did not find anything about **enable logging** queries on MongoDB side

Do you know if we have this feature?

**Comment by zookzook** [comment]
Hi,

no, we don't. But you can link to the documentation of that feature and if I find some time, I add the feature to the driver.

**Comment by joeapearson** [comment]
@joaovbibiano you can do this with the `Mongo.admin_command` API I think.  Something like this:

```
# Get log level
iex> Mongo.admin_command(:topology_name, getParameter: 1, logLevel: 1)

# Set log level
iex> Mongo.admin_command(:topology_name, setParameter:1, logLevel: 2)
```
There are various other log parameters you can control, see https://docs.mongodb.com/manual/reference/parameters/

This will only help for changing the log output of mongodb itself (very useful for debugging but maybe not quite what you want).

**Comment by joaovbibiano** [comment]
Hey @joeapearson  and @zookzook 

Thanks for your response and time here!

@joeapearson I have many apps connected to this database, in this way, I can't change the logLevel for the mongo side. I need just a change for my application (elixir).

In Ruby, I configured the logs format through `Mongo::Logger.logger` property. That's what I need.

**Comment by zookzook** [comment]
If I you understand you, you want to have some logging output within the driver itself, so das the driver echos some logging information into the the Elixir logging facility?

**Comment by zookzook** [comment]
I think there is a option for providing a name for the hand-shake-workflow:

`{:ok, top} = Mongo.start_link(database: "my-db", seeds: seeds, appname: "getting rich")`

From the readme:

`:appname` - The name of the application used the driver for the MongoDB-Handshake

Maybe you can use this option.

**Comment by joaovbibiano** [comment]
I'll elaborate on a better example, then I return you

**Comment by zookzook** [comment]
Ping!

**Comment by joaovbibiano** [comment]
Sorry for the delay...

Using the `appname` I got a log yes, but just on Handshake

I want to log all my queries to keep it inside my Kibana

**Comment by zookzook** [comment]
Closing due to no response.

**Comment by zookzook** [comment]
I added support for telemetry and logging. Feel free to check the master branch.
